[package]
name = "kaspaverse_bridge"
version = "0.1.0"
edition = "2021"
license.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.12.0"
kaspaverse-chain = { version = "0.1.0", path = "../chain" }
tokio.workspace = true
log.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
