// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/dag.dart';
import 'api/error.dart';
import 'api/vault.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiAppInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1163459127;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'kaspaverse_bridge',
        ioDirectory: 'rust/bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiVaultAbandonCreate();

  Future<void> crateApiVaultBeginCreate();

  Future<DagSnapshot> crateApiDagDagSnapshotDefault();

  Future<void> crateApiAppInitApp();

  Future<void> crateApiVaultInitVault({required String appPrivateDir});

  Future<BigInt> crateApiVaultKdfBenchMs({required VaultKdfParams params});

  Future<void> crateApiVaultLockVault();

  Future<void> crateApiVaultRestoreAndPersist({
    required List<int> phrase,
    required List<int> extraWord,
    required List<int> passphrase,
    required VaultKdfParams params,
  });

  Future<String> crateApiVaultRestorePreview({
    required List<int> phrase,
    required List<int> extraWord,
  });

  Future<void> crateApiVaultSealAndPersist({
    required List<int> passphrase,
    required List<int> extraWord,
    required VaultKdfParams params,
  });

  Stream<DagSnapshot> crateApiDagSubscribeDagUpdates();

  Future<void> crateApiVaultUnlockWithPassphrase({
    required List<int> passphrase,
  });

  Future<bool> crateApiVaultVaultExists();

  Future<VaultKdfParams> crateApiVaultVaultKdfParamsStartingGrid();

  Future<VaultKdfParams> crateApiVaultVaultKdfParamsTuned();

  Future<VaultStatus> crateApiVaultVaultStatusDefault();

  Stream<VaultStatus> crateApiVaultVaultStatusStream();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiVaultAbandonCreate() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultAbandonCreateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultAbandonCreateConstMeta =>
      const TaskConstMeta(debugName: "abandon_create", argNames: []);

  @override
  Future<void> crateApiVaultBeginCreate() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiVaultBeginCreateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultBeginCreateConstMeta =>
      const TaskConstMeta(debugName: "begin_create", argNames: []);

  @override
  Future<DagSnapshot> crateApiDagDagSnapshotDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_dag_snapshot,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDagDagSnapshotDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDagDagSnapshotDefaultConstMeta =>
      const TaskConstMeta(debugName: "dag_snapshot_default", argNames: []);

  @override
  Future<void> crateApiAppInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiVaultInitVault({required String appPrivateDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(appPrivateDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiVaultInitVaultConstMeta,
        argValues: [appPrivateDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultInitVaultConstMeta =>
      const TaskConstMeta(debugName: "init_vault", argNames: ["appPrivateDir"]);

  @override
  Future<BigInt> crateApiVaultKdfBenchMs({required VaultKdfParams params}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_vault_kdf_params(params, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiVaultKdfBenchMsConstMeta,
        argValues: [params],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultKdfBenchMsConstMeta =>
      const TaskConstMeta(debugName: "kdf_bench_ms", argNames: ["params"]);

  @override
  Future<void> crateApiVaultLockVault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultLockVaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultLockVaultConstMeta =>
      const TaskConstMeta(debugName: "lock_vault", argNames: []);

  @override
  Future<void> crateApiVaultRestoreAndPersist({
    required List<int> phrase,
    required List<int> extraWord,
    required List<int> passphrase,
    required VaultKdfParams params,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(phrase, serializer);
          sse_encode_list_prim_u_8_loose(extraWord, serializer);
          sse_encode_list_prim_u_8_loose(passphrase, serializer);
          sse_encode_box_autoadd_vault_kdf_params(params, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiVaultRestoreAndPersistConstMeta,
        argValues: [phrase, extraWord, passphrase, params],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultRestoreAndPersistConstMeta =>
      const TaskConstMeta(
        debugName: "restore_and_persist",
        argNames: ["phrase", "extraWord", "passphrase", "params"],
      );

  @override
  Future<String> crateApiVaultRestorePreview({
    required List<int> phrase,
    required List<int> extraWord,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(phrase, serializer);
          sse_encode_list_prim_u_8_loose(extraWord, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiVaultRestorePreviewConstMeta,
        argValues: [phrase, extraWord],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultRestorePreviewConstMeta =>
      const TaskConstMeta(
        debugName: "restore_preview",
        argNames: ["phrase", "extraWord"],
      );

  @override
  Future<void> crateApiVaultSealAndPersist({
    required List<int> passphrase,
    required List<int> extraWord,
    required VaultKdfParams params,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(passphrase, serializer);
          sse_encode_list_prim_u_8_loose(extraWord, serializer);
          sse_encode_box_autoadd_vault_kdf_params(params, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiVaultSealAndPersistConstMeta,
        argValues: [passphrase, extraWord, params],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultSealAndPersistConstMeta =>
      const TaskConstMeta(
        debugName: "seal_and_persist",
        argNames: ["passphrase", "extraWord", "params"],
      );

  @override
  Stream<DagSnapshot> crateApiDagSubscribeDagUpdates() {
    final sink = RustStreamSink<DagSnapshot>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_dag_snapshot_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 11,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_app_error,
          ),
          constMeta: kCrateApiDagSubscribeDagUpdatesConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDagSubscribeDagUpdatesConstMeta =>
      const TaskConstMeta(
        debugName: "subscribe_dag_updates",
        argNames: ["sink"],
      );

  @override
  Future<void> crateApiVaultUnlockWithPassphrase({
    required List<int> passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiVaultUnlockWithPassphraseConstMeta,
        argValues: [passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultUnlockWithPassphraseConstMeta =>
      const TaskConstMeta(
        debugName: "unlock_with_passphrase",
        argNames: ["passphrase"],
      );

  @override
  Future<bool> crateApiVaultVaultExists() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultVaultExistsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultExistsConstMeta =>
      const TaskConstMeta(debugName: "vault_exists", argNames: []);

  @override
  Future<VaultKdfParams> crateApiVaultVaultKdfParamsStartingGrid() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_kdf_params,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultVaultKdfParamsStartingGridConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultKdfParamsStartingGridConstMeta =>
      const TaskConstMeta(
        debugName: "vault_kdf_params_starting_grid",
        argNames: [],
      );

  @override
  Future<VaultKdfParams> crateApiVaultVaultKdfParamsTuned() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_kdf_params,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultVaultKdfParamsTunedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultKdfParamsTunedConstMeta =>
      const TaskConstMeta(debugName: "vault_kdf_params_tuned", argNames: []);

  @override
  Future<VaultStatus> crateApiVaultVaultStatusDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultVaultStatusDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultStatusDefaultConstMeta =>
      const TaskConstMeta(debugName: "vault_status_default", argNames: []);

  @override
  Stream<VaultStatus> crateApiVaultVaultStatusStream() {
    final sink = RustStreamSink<VaultStatus>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_vault_status_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 17,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_app_error,
          ),
          constMeta: kCrateApiVaultVaultStatusStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiVaultVaultStatusStreamConstMeta =>
      const TaskConstMeta(debugName: "vault_status_stream", argNames: ["sink"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<DagSnapshot> dco_decode_StreamSink_dag_snapshot_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<VaultStatus> dco_decode_StreamSink_vault_status_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppError dco_decode_app_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return AppError(message: dco_decode_String(arr[0]));
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  VaultKdfParams dco_decode_box_autoadd_vault_kdf_params(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_vault_kdf_params(raw);
  }

  @protected
  DagSnapshot dco_decode_dag_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DagSnapshot(
      connected: dco_decode_bool(arr[0]),
      endpoint: dco_decode_opt_String(arr[1]),
      virtualDaaScore: dco_decode_opt_box_autoadd_u_64(arr[2]),
      sinkBlueScore: dco_decode_opt_box_autoadd_u_64(arr[3]),
    );
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VaultKdfParams dco_decode_vault_kdf_params(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return VaultKdfParams(
      mCostKib: dco_decode_u_32(arr[0]),
      tCost: dco_decode_u_32(arr[1]),
      pCost: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  VaultStatus dco_decode_vault_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VaultStatus(
      exists: dco_decode_bool(arr[0]),
      unlocked: dco_decode_bool(arr[1]),
      lockedOutUntilUnix: dco_decode_opt_box_autoadd_u_64(arr[2]),
      failedAttempts: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<DagSnapshot> sse_decode_StreamSink_dag_snapshot_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<VaultStatus> sse_decode_StreamSink_vault_status_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppError sse_decode_app_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_message = sse_decode_String(deserializer);
    return AppError(message: var_message);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  VaultKdfParams sse_decode_box_autoadd_vault_kdf_params(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_vault_kdf_params(deserializer));
  }

  @protected
  DagSnapshot sse_decode_dag_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_connected = sse_decode_bool(deserializer);
    var var_endpoint = sse_decode_opt_String(deserializer);
    var var_virtualDaaScore = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_sinkBlueScore = sse_decode_opt_box_autoadd_u_64(deserializer);
    return DagSnapshot(
      connected: var_connected,
      endpoint: var_endpoint,
      virtualDaaScore: var_virtualDaaScore,
      sinkBlueScore: var_sinkBlueScore,
    );
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VaultKdfParams sse_decode_vault_kdf_params(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mCostKib = sse_decode_u_32(deserializer);
    var var_tCost = sse_decode_u_32(deserializer);
    var var_pCost = sse_decode_u_32(deserializer);
    return VaultKdfParams(
      mCostKib: var_mCostKib,
      tCost: var_tCost,
      pCost: var_pCost,
    );
  }

  @protected
  VaultStatus sse_decode_vault_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_exists = sse_decode_bool(deserializer);
    var var_unlocked = sse_decode_bool(deserializer);
    var var_lockedOutUntilUnix = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_failedAttempts = sse_decode_u_32(deserializer);
    return VaultStatus(
      exists: var_exists,
      unlocked: var_unlocked,
      lockedOutUntilUnix: var_lockedOutUntilUnix,
      failedAttempts: var_failedAttempts,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_dag_snapshot_Sse(
    RustStreamSink<DagSnapshot> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_dag_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_vault_status_Sse(
    RustStreamSink<VaultStatus> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_error(AppError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_vault_kdf_params(
    VaultKdfParams self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_vault_kdf_params(self, serializer);
  }

  @protected
  void sse_encode_dag_snapshot(DagSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.connected, serializer);
    sse_encode_opt_String(self.endpoint, serializer);
    sse_encode_opt_box_autoadd_u_64(self.virtualDaaScore, serializer);
    sse_encode_opt_box_autoadd_u_64(self.sinkBlueScore, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_vault_kdf_params(
    VaultKdfParams self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.mCostKib, serializer);
    sse_encode_u_32(self.tCost, serializer);
    sse_encode_u_32(self.pCost, serializer);
  }

  @protected
  void sse_encode_vault_status(VaultStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.exists, serializer);
    sse_encode_bool(self.unlocked, serializer);
    sse_encode_opt_box_autoadd_u_64(self.lockedOutUntilUnix, serializer);
    sse_encode_u_32(self.failedAttempts, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
