// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/dag.dart';
import 'api/error.dart';
import 'api/send.dart';
import 'api/transport.dart';
import 'api/vault.dart';
import 'api/wallet.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<DagSnapshot> dco_decode_StreamSink_dag_snapshot_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<TransportEventDto>
  dco_decode_StreamSink_transport_event_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<VaultStatus> dco_decode_StreamSink_vault_status_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<WalletSnapshot> dco_decode_StreamSink_wallet_snapshot_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ActivityDirection dco_decode_activity_direction(dynamic raw);

  @protected
  ActivityRecord dco_decode_activity_record(dynamic raw);

  @protected
  AppError dco_decode_app_error(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  VaultKdfParams dco_decode_box_autoadd_vault_kdf_params(dynamic raw);

  @protected
  ConversationDto dco_decode_conversation_dto(dynamic raw);

  @protected
  DagSnapshot dco_decode_dag_snapshot(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ActivityRecord> dco_decode_list_activity_record(dynamic raw);

  @protected
  List<ConversationDto> dco_decode_list_conversation_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ThreadMessageDto> dco_decode_list_thread_message_dto(dynamic raw);

  @protected
  MaturityState dco_decode_maturity_state(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  SendOutcomeDto dco_decode_send_outcome_dto(dynamic raw);

  @protected
  SendSummaryDto dco_decode_send_summary_dto(dynamic raw);

  @protected
  ThreadMessageDto dco_decode_thread_message_dto(dynamic raw);

  @protected
  TransportEventDto dco_decode_transport_event_dto(dynamic raw);

  @protected
  TransportSendSummaryDto dco_decode_transport_send_summary_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VaultKdfParams dco_decode_vault_kdf_params(dynamic raw);

  @protected
  VaultStatus dco_decode_vault_status(dynamic raw);

  @protected
  WalletSnapshot dco_decode_wallet_snapshot(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<DagSnapshot> sse_decode_StreamSink_dag_snapshot_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TransportEventDto>
  sse_decode_StreamSink_transport_event_dto_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<VaultStatus> sse_decode_StreamSink_vault_status_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<WalletSnapshot> sse_decode_StreamSink_wallet_snapshot_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActivityDirection sse_decode_activity_direction(SseDeserializer deserializer);

  @protected
  ActivityRecord sse_decode_activity_record(SseDeserializer deserializer);

  @protected
  AppError sse_decode_app_error(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  VaultKdfParams sse_decode_box_autoadd_vault_kdf_params(
    SseDeserializer deserializer,
  );

  @protected
  ConversationDto sse_decode_conversation_dto(SseDeserializer deserializer);

  @protected
  DagSnapshot sse_decode_dag_snapshot(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ActivityRecord> sse_decode_list_activity_record(
    SseDeserializer deserializer,
  );

  @protected
  List<ConversationDto> sse_decode_list_conversation_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ThreadMessageDto> sse_decode_list_thread_message_dto(
    SseDeserializer deserializer,
  );

  @protected
  MaturityState sse_decode_maturity_state(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  SendOutcomeDto sse_decode_send_outcome_dto(SseDeserializer deserializer);

  @protected
  SendSummaryDto sse_decode_send_summary_dto(SseDeserializer deserializer);

  @protected
  ThreadMessageDto sse_decode_thread_message_dto(SseDeserializer deserializer);

  @protected
  TransportEventDto sse_decode_transport_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  TransportSendSummaryDto sse_decode_transport_send_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VaultKdfParams sse_decode_vault_kdf_params(SseDeserializer deserializer);

  @protected
  VaultStatus sse_decode_vault_status(SseDeserializer deserializer);

  @protected
  WalletSnapshot sse_decode_wallet_snapshot(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_dag_snapshot_Sse(
    RustStreamSink<DagSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_transport_event_dto_Sse(
    RustStreamSink<TransportEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_vault_status_Sse(
    RustStreamSink<VaultStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_wallet_snapshot_Sse(
    RustStreamSink<WalletSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_activity_direction(
    ActivityDirection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_activity_record(
    ActivityRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_app_error(AppError self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vault_kdf_params(
    VaultKdfParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_dto(
    ConversationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dag_snapshot(DagSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_activity_record(
    List<ActivityRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_conversation_dto(
    List<ConversationDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_thread_message_dto(
    List<ThreadMessageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_maturity_state(MaturityState self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_send_outcome_dto(
    SendOutcomeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_send_summary_dto(
    SendSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_thread_message_dto(
    ThreadMessageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transport_event_dto(
    TransportEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transport_send_summary_dto(
    TransportSendSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_vault_kdf_params(
    VaultKdfParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vault_status(VaultStatus self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_snapshot(
    WalletSnapshot self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
