// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/dag.dart';
import 'api/error.dart';
import 'api/send.dart';
import 'api/vault.dart';
import 'api/wallet.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiAppInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1472710135;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'kaspaverse_bridge',
        ioDirectory: 'rust/bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiVaultAbandonCreate();

  Future<void> crateApiVaultBeginCreate();

  Future<DagSnapshot> crateApiDagDagSnapshotDefault();

  Future<void> crateApiAppInitApp();

  Future<void> crateApiVaultInitVault({required String appPrivateDir});

  Future<BigInt> crateApiVaultKdfBenchMs({required VaultKdfParams params});

  Future<void> crateApiVaultLockVault();

  Future<void> crateApiVaultRestoreAndPersist({
    required List<int> phrase,
    required List<int> extraWord,
    required List<int> passphrase,
    required VaultKdfParams params,
  });

  Future<String> crateApiVaultRestorePreview({
    required List<int> phrase,
    required List<int> extraWord,
  });

  Future<void> crateApiVaultSealAndPersist({
    required List<int> passphrase,
    required List<int> extraWord,
    required VaultKdfParams params,
  });

  Future<void> crateApiSendSendAbandon();

  Future<SendOutcomeDto> crateApiSendSendCommit({required BigInt nonce});

  Future<SendSummaryDto> crateApiSendSendPrepare({
    required String destination,
    required BigInt amountSompi,
  });

  Stream<DagSnapshot> crateApiDagSubscribeDagUpdates();

  Stream<WalletSnapshot> crateApiWalletSubscribeWalletUpdates();

  Future<void> crateApiVaultUnlockWithPassphrase({
    required List<int> passphrase,
  });

  Future<bool> crateApiVaultVaultExists();

  Future<VaultKdfParams> crateApiVaultVaultKdfParamsStartingGrid();

  Future<VaultKdfParams> crateApiVaultVaultKdfParamsTuned();

  Future<String> crateApiVaultVaultReceiveAddress();

  Future<VaultStatus> crateApiVaultVaultStatusDefault();

  Stream<VaultStatus> crateApiVaultVaultStatusStream();

  Future<WalletSnapshot> crateApiWalletWalletSnapshotDefault();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiVaultAbandonCreate() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultAbandonCreateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultAbandonCreateConstMeta =>
      const TaskConstMeta(debugName: "abandon_create", argNames: []);

  @override
  Future<void> crateApiVaultBeginCreate() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiVaultBeginCreateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultBeginCreateConstMeta =>
      const TaskConstMeta(debugName: "begin_create", argNames: []);

  @override
  Future<DagSnapshot> crateApiDagDagSnapshotDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_dag_snapshot,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDagDagSnapshotDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDagDagSnapshotDefaultConstMeta =>
      const TaskConstMeta(debugName: "dag_snapshot_default", argNames: []);

  @override
  Future<void> crateApiAppInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiVaultInitVault({required String appPrivateDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(appPrivateDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiVaultInitVaultConstMeta,
        argValues: [appPrivateDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultInitVaultConstMeta =>
      const TaskConstMeta(debugName: "init_vault", argNames: ["appPrivateDir"]);

  @override
  Future<BigInt> crateApiVaultKdfBenchMs({required VaultKdfParams params}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_vault_kdf_params(params, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiVaultKdfBenchMsConstMeta,
        argValues: [params],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultKdfBenchMsConstMeta =>
      const TaskConstMeta(debugName: "kdf_bench_ms", argNames: ["params"]);

  @override
  Future<void> crateApiVaultLockVault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultLockVaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultLockVaultConstMeta =>
      const TaskConstMeta(debugName: "lock_vault", argNames: []);

  @override
  Future<void> crateApiVaultRestoreAndPersist({
    required List<int> phrase,
    required List<int> extraWord,
    required List<int> passphrase,
    required VaultKdfParams params,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(phrase, serializer);
          sse_encode_list_prim_u_8_loose(extraWord, serializer);
          sse_encode_list_prim_u_8_loose(passphrase, serializer);
          sse_encode_box_autoadd_vault_kdf_params(params, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiVaultRestoreAndPersistConstMeta,
        argValues: [phrase, extraWord, passphrase, params],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultRestoreAndPersistConstMeta =>
      const TaskConstMeta(
        debugName: "restore_and_persist",
        argNames: ["phrase", "extraWord", "passphrase", "params"],
      );

  @override
  Future<String> crateApiVaultRestorePreview({
    required List<int> phrase,
    required List<int> extraWord,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(phrase, serializer);
          sse_encode_list_prim_u_8_loose(extraWord, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiVaultRestorePreviewConstMeta,
        argValues: [phrase, extraWord],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultRestorePreviewConstMeta =>
      const TaskConstMeta(
        debugName: "restore_preview",
        argNames: ["phrase", "extraWord"],
      );

  @override
  Future<void> crateApiVaultSealAndPersist({
    required List<int> passphrase,
    required List<int> extraWord,
    required VaultKdfParams params,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(passphrase, serializer);
          sse_encode_list_prim_u_8_loose(extraWord, serializer);
          sse_encode_box_autoadd_vault_kdf_params(params, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiVaultSealAndPersistConstMeta,
        argValues: [passphrase, extraWord, params],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultSealAndPersistConstMeta =>
      const TaskConstMeta(
        debugName: "seal_and_persist",
        argNames: ["passphrase", "extraWord", "params"],
      );

  @override
  Future<void> crateApiSendSendAbandon() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSendSendAbandonConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendSendAbandonConstMeta =>
      const TaskConstMeta(debugName: "send_abandon", argNames: []);

  @override
  Future<SendOutcomeDto> crateApiSendSendCommit({required BigInt nonce}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(nonce, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_send_outcome_dto,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiSendSendCommitConstMeta,
        argValues: [nonce],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendSendCommitConstMeta =>
      const TaskConstMeta(debugName: "send_commit", argNames: ["nonce"]);

  @override
  Future<SendSummaryDto> crateApiSendSendPrepare({
    required String destination,
    required BigInt amountSompi,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(destination, serializer);
          sse_encode_u_64(amountSompi, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_send_summary_dto,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiSendSendPrepareConstMeta,
        argValues: [destination, amountSompi],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendSendPrepareConstMeta => const TaskConstMeta(
    debugName: "send_prepare",
    argNames: ["destination", "amountSompi"],
  );

  @override
  Stream<DagSnapshot> crateApiDagSubscribeDagUpdates() {
    final sink = RustStreamSink<DagSnapshot>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_dag_snapshot_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 14,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_app_error,
          ),
          constMeta: kCrateApiDagSubscribeDagUpdatesConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDagSubscribeDagUpdatesConstMeta =>
      const TaskConstMeta(
        debugName: "subscribe_dag_updates",
        argNames: ["sink"],
      );

  @override
  Stream<WalletSnapshot> crateApiWalletSubscribeWalletUpdates() {
    final sink = RustStreamSink<WalletSnapshot>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_wallet_snapshot_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 15,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_app_error,
          ),
          constMeta: kCrateApiWalletSubscribeWalletUpdatesConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiWalletSubscribeWalletUpdatesConstMeta =>
      const TaskConstMeta(
        debugName: "subscribe_wallet_updates",
        argNames: ["sink"],
      );

  @override
  Future<void> crateApiVaultUnlockWithPassphrase({
    required List<int> passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiVaultUnlockWithPassphraseConstMeta,
        argValues: [passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultUnlockWithPassphraseConstMeta =>
      const TaskConstMeta(
        debugName: "unlock_with_passphrase",
        argNames: ["passphrase"],
      );

  @override
  Future<bool> crateApiVaultVaultExists() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultVaultExistsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultExistsConstMeta =>
      const TaskConstMeta(debugName: "vault_exists", argNames: []);

  @override
  Future<VaultKdfParams> crateApiVaultVaultKdfParamsStartingGrid() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_kdf_params,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultVaultKdfParamsStartingGridConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultKdfParamsStartingGridConstMeta =>
      const TaskConstMeta(
        debugName: "vault_kdf_params_starting_grid",
        argNames: [],
      );

  @override
  Future<VaultKdfParams> crateApiVaultVaultKdfParamsTuned() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_kdf_params,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultVaultKdfParamsTunedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultKdfParamsTunedConstMeta =>
      const TaskConstMeta(debugName: "vault_kdf_params_tuned", argNames: []);

  @override
  Future<String> crateApiVaultVaultReceiveAddress() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_app_error,
        ),
        constMeta: kCrateApiVaultVaultReceiveAddressConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultReceiveAddressConstMeta =>
      const TaskConstMeta(debugName: "vault_receive_address", argNames: []);

  @override
  Future<VaultStatus> crateApiVaultVaultStatusDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultVaultStatusDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultStatusDefaultConstMeta =>
      const TaskConstMeta(debugName: "vault_status_default", argNames: []);

  @override
  Stream<VaultStatus> crateApiVaultVaultStatusStream() {
    final sink = RustStreamSink<VaultStatus>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_vault_status_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 22,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_app_error,
          ),
          constMeta: kCrateApiVaultVaultStatusStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiVaultVaultStatusStreamConstMeta =>
      const TaskConstMeta(debugName: "vault_status_stream", argNames: ["sink"]);

  @override
  Future<WalletSnapshot> crateApiWalletWalletSnapshotDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wallet_snapshot,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWalletWalletSnapshotDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletWalletSnapshotDefaultConstMeta =>
      const TaskConstMeta(debugName: "wallet_snapshot_default", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<DagSnapshot> dco_decode_StreamSink_dag_snapshot_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<VaultStatus> dco_decode_StreamSink_vault_status_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<WalletSnapshot> dco_decode_StreamSink_wallet_snapshot_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ActivityDirection dco_decode_activity_direction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ActivityDirection.values[raw as int];
  }

  @protected
  ActivityRecord dco_decode_activity_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ActivityRecord(
      txid: dco_decode_String(arr[0]),
      valueSompi: dco_decode_u_64(arr[1]),
      unixtimeMsec: dco_decode_opt_box_autoadd_u_64(arr[2]),
      blockDaaScore: dco_decode_u_64(arr[3]),
      direction: dco_decode_activity_direction(arr[4]),
      isCoinbase: dco_decode_bool(arr[5]),
      maturity: dco_decode_maturity_state(arr[6]),
    );
  }

  @protected
  AppError dco_decode_app_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return AppError(message: dco_decode_String(arr[0]));
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  VaultKdfParams dco_decode_box_autoadd_vault_kdf_params(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_vault_kdf_params(raw);
  }

  @protected
  DagSnapshot dco_decode_dag_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DagSnapshot(
      connected: dco_decode_bool(arr[0]),
      endpoint: dco_decode_opt_String(arr[1]),
      virtualDaaScore: dco_decode_opt_box_autoadd_u_64(arr[2]),
      sinkBlueScore: dco_decode_opt_box_autoadd_u_64(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<ActivityRecord> dco_decode_list_activity_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_activity_record).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MaturityState dco_decode_maturity_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MaturityState.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  SendOutcomeDto dco_decode_send_outcome_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SendOutcomeDto(
      finalTxid: dco_decode_opt_String(arr[0]),
      submitted: dco_decode_u_32(arr[1]),
      total: dco_decode_u_32(arr[2]),
      partial: dco_decode_bool(arr[3]),
      error: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  SendSummaryDto dco_decode_send_summary_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return SendSummaryDto(
      nonce: dco_decode_u_64(arr[0]),
      destination: dco_decode_String(arr[1]),
      amountSompi: dco_decode_u_64(arr[2]),
      feeSompi: dco_decode_u_64(arr[3]),
      totalSompi: dco_decode_u_64(arr[4]),
      mass: dco_decode_u_64(arr[5]),
      txCount: dco_decode_u_32(arr[6]),
      utxoCount: dco_decode_u_32(arr[7]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VaultKdfParams dco_decode_vault_kdf_params(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return VaultKdfParams(
      mCostKib: dco_decode_u_32(arr[0]),
      tCost: dco_decode_u_32(arr[1]),
      pCost: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  VaultStatus dco_decode_vault_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VaultStatus(
      exists: dco_decode_bool(arr[0]),
      unlocked: dco_decode_bool(arr[1]),
      lockedOutUntilUnix: dco_decode_opt_box_autoadd_u_64(arr[2]),
      failedAttempts: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  WalletSnapshot dco_decode_wallet_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return WalletSnapshot(
      connected: dco_decode_bool(arr[0]),
      syncing: dco_decode_bool(arr[1]),
      utxoIndexMissing: dco_decode_bool(arr[2]),
      matureSompi: dco_decode_opt_box_autoadd_u_64(arr[3]),
      pendingSompi: dco_decode_opt_box_autoadd_u_64(arr[4]),
      outgoingSompi: dco_decode_opt_box_autoadd_u_64(arr[5]),
      activity: dco_decode_list_activity_record(arr[6]),
      error: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<DagSnapshot> sse_decode_StreamSink_dag_snapshot_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<VaultStatus> sse_decode_StreamSink_vault_status_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<WalletSnapshot> sse_decode_StreamSink_wallet_snapshot_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ActivityDirection sse_decode_activity_direction(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ActivityDirection.values[inner];
  }

  @protected
  ActivityRecord sse_decode_activity_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_txid = sse_decode_String(deserializer);
    var var_valueSompi = sse_decode_u_64(deserializer);
    var var_unixtimeMsec = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_blockDaaScore = sse_decode_u_64(deserializer);
    var var_direction = sse_decode_activity_direction(deserializer);
    var var_isCoinbase = sse_decode_bool(deserializer);
    var var_maturity = sse_decode_maturity_state(deserializer);
    return ActivityRecord(
      txid: var_txid,
      valueSompi: var_valueSompi,
      unixtimeMsec: var_unixtimeMsec,
      blockDaaScore: var_blockDaaScore,
      direction: var_direction,
      isCoinbase: var_isCoinbase,
      maturity: var_maturity,
    );
  }

  @protected
  AppError sse_decode_app_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_message = sse_decode_String(deserializer);
    return AppError(message: var_message);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  VaultKdfParams sse_decode_box_autoadd_vault_kdf_params(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_vault_kdf_params(deserializer));
  }

  @protected
  DagSnapshot sse_decode_dag_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_connected = sse_decode_bool(deserializer);
    var var_endpoint = sse_decode_opt_String(deserializer);
    var var_virtualDaaScore = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_sinkBlueScore = sse_decode_opt_box_autoadd_u_64(deserializer);
    return DagSnapshot(
      connected: var_connected,
      endpoint: var_endpoint,
      virtualDaaScore: var_virtualDaaScore,
      sinkBlueScore: var_sinkBlueScore,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<ActivityRecord> sse_decode_list_activity_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ActivityRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_activity_record(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MaturityState sse_decode_maturity_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MaturityState.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SendOutcomeDto sse_decode_send_outcome_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_finalTxid = sse_decode_opt_String(deserializer);
    var var_submitted = sse_decode_u_32(deserializer);
    var var_total = sse_decode_u_32(deserializer);
    var var_partial = sse_decode_bool(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return SendOutcomeDto(
      finalTxid: var_finalTxid,
      submitted: var_submitted,
      total: var_total,
      partial: var_partial,
      error: var_error,
    );
  }

  @protected
  SendSummaryDto sse_decode_send_summary_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nonce = sse_decode_u_64(deserializer);
    var var_destination = sse_decode_String(deserializer);
    var var_amountSompi = sse_decode_u_64(deserializer);
    var var_feeSompi = sse_decode_u_64(deserializer);
    var var_totalSompi = sse_decode_u_64(deserializer);
    var var_mass = sse_decode_u_64(deserializer);
    var var_txCount = sse_decode_u_32(deserializer);
    var var_utxoCount = sse_decode_u_32(deserializer);
    return SendSummaryDto(
      nonce: var_nonce,
      destination: var_destination,
      amountSompi: var_amountSompi,
      feeSompi: var_feeSompi,
      totalSompi: var_totalSompi,
      mass: var_mass,
      txCount: var_txCount,
      utxoCount: var_utxoCount,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VaultKdfParams sse_decode_vault_kdf_params(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mCostKib = sse_decode_u_32(deserializer);
    var var_tCost = sse_decode_u_32(deserializer);
    var var_pCost = sse_decode_u_32(deserializer);
    return VaultKdfParams(
      mCostKib: var_mCostKib,
      tCost: var_tCost,
      pCost: var_pCost,
    );
  }

  @protected
  VaultStatus sse_decode_vault_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_exists = sse_decode_bool(deserializer);
    var var_unlocked = sse_decode_bool(deserializer);
    var var_lockedOutUntilUnix = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_failedAttempts = sse_decode_u_32(deserializer);
    return VaultStatus(
      exists: var_exists,
      unlocked: var_unlocked,
      lockedOutUntilUnix: var_lockedOutUntilUnix,
      failedAttempts: var_failedAttempts,
    );
  }

  @protected
  WalletSnapshot sse_decode_wallet_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_connected = sse_decode_bool(deserializer);
    var var_syncing = sse_decode_bool(deserializer);
    var var_utxoIndexMissing = sse_decode_bool(deserializer);
    var var_matureSompi = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_pendingSompi = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_outgoingSompi = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_activity = sse_decode_list_activity_record(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return WalletSnapshot(
      connected: var_connected,
      syncing: var_syncing,
      utxoIndexMissing: var_utxoIndexMissing,
      matureSompi: var_matureSompi,
      pendingSompi: var_pendingSompi,
      outgoingSompi: var_outgoingSompi,
      activity: var_activity,
      error: var_error,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_dag_snapshot_Sse(
    RustStreamSink<DagSnapshot> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_dag_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_vault_status_Sse(
    RustStreamSink<VaultStatus> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_wallet_snapshot_Sse(
    RustStreamSink<WalletSnapshot> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_wallet_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_activity_direction(
    ActivityDirection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_activity_record(
    ActivityRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.txid, serializer);
    sse_encode_u_64(self.valueSompi, serializer);
    sse_encode_opt_box_autoadd_u_64(self.unixtimeMsec, serializer);
    sse_encode_u_64(self.blockDaaScore, serializer);
    sse_encode_activity_direction(self.direction, serializer);
    sse_encode_bool(self.isCoinbase, serializer);
    sse_encode_maturity_state(self.maturity, serializer);
  }

  @protected
  void sse_encode_app_error(AppError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_vault_kdf_params(
    VaultKdfParams self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_vault_kdf_params(self, serializer);
  }

  @protected
  void sse_encode_dag_snapshot(DagSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.connected, serializer);
    sse_encode_opt_String(self.endpoint, serializer);
    sse_encode_opt_box_autoadd_u_64(self.virtualDaaScore, serializer);
    sse_encode_opt_box_autoadd_u_64(self.sinkBlueScore, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_activity_record(
    List<ActivityRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_activity_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_maturity_state(MaturityState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_send_outcome_dto(
    SendOutcomeDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.finalTxid, serializer);
    sse_encode_u_32(self.submitted, serializer);
    sse_encode_u_32(self.total, serializer);
    sse_encode_bool(self.partial, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_send_summary_dto(
    SendSummaryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.nonce, serializer);
    sse_encode_String(self.destination, serializer);
    sse_encode_u_64(self.amountSompi, serializer);
    sse_encode_u_64(self.feeSompi, serializer);
    sse_encode_u_64(self.totalSompi, serializer);
    sse_encode_u_64(self.mass, serializer);
    sse_encode_u_32(self.txCount, serializer);
    sse_encode_u_32(self.utxoCount, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_vault_kdf_params(
    VaultKdfParams self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.mCostKib, serializer);
    sse_encode_u_32(self.tCost, serializer);
    sse_encode_u_32(self.pCost, serializer);
  }

  @protected
  void sse_encode_vault_status(VaultStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.exists, serializer);
    sse_encode_bool(self.unlocked, serializer);
    sse_encode_opt_box_autoadd_u_64(self.lockedOutUntilUnix, serializer);
    sse_encode_u_32(self.failedAttempts, serializer);
  }

  @protected
  void sse_encode_wallet_snapshot(
    WalletSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.connected, serializer);
    sse_encode_bool(self.syncing, serializer);
    sse_encode_bool(self.utxoIndexMissing, serializer);
    sse_encode_opt_box_autoadd_u_64(self.matureSompi, serializer);
    sse_encode_opt_box_autoadd_u_64(self.pendingSompi, serializer);
    sse_encode_opt_box_autoadd_u_64(self.outgoingSompi, serializer);
    sse_encode_list_activity_record(self.activity, serializer);
    sse_encode_opt_String(self.error, serializer);
  }
}
