//! The platform vault session (P1.2) — the one process-wide handle to the
//! unlocked custody engine, reachable by BOTH constitutional lanes:
//!
//! - **Path B** (passphrase) over FRB: `Uint8List` in, Argon2id → XChaCha20
//!   unseal, here. The passphrase is zeroized the moment this code is done.
//! - **Path A** (biometric) over JNI (`jni_seed`, Android-only): the Keystore
//!   Cipher's plaintext seed crosses Kotlin → Rust and loads the same vault.
//!
//! A process-wide singleton is deliberate, not the L6 anti-pattern: two
//! independent lanes (FRB and JNI) must observe ONE vault, so a shared handle
//! is required, not merely convenient. The lock is poison-recovering (L7) — its
//! contents are an all-or-nothing `Option`, safe to recover after a panic.
//!
//! Nothing secret-shaped crosses to Dart: every public fn returns `()`, `bool`,
//! `VaultStatus` (bools + non-secret counters), or `Result<_, AppError>`.

use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::sync::{Mutex, OnceLock, PoisonError};
use std::time::{SystemTime, UNIX_EPOCH};

use kaspaverse_chain::Address;
use kaspaverse_core::{
    seal_seed, unseal_seed, Branch, KeyChain, MnemonicCeremony, Prefix, SealParams, SecretSeed,
    UnlockedVault, VaultSigner,
};
use tokio::sync::broadcast::{self, error::RecvError};
use zeroize::Zeroizing;

use crate::api::error::AppError;
use crate::frb_generated::StreamSink;

// ── Process-wide state ────────────────────────────────────────────────────

/// The sole strong owner of the unlocked vault (None = locked).
static VAULT: Mutex<Option<UnlockedVault>> = Mutex::new(None);
/// App-private directory the platform hands us at init; the sealed blob and the
/// lockout counter live here (INV-3 — never SharedPreferences).
static VAULT_DIR: Mutex<Option<PathBuf>> = Mutex::new(None);
/// Status fan-out; lazily created so `send` works without a runtime.
static STATUS_TX: OnceLock<broadcast::Sender<VaultStatus>> = OnceLock::new();

/// The live mnemonic during a P1.4 create ceremony (D-038): generated by
/// [`begin_create`], displayed by the native FLAG_SECURE reveal/verify surface
/// over the JNI lane (D-037 — words never cross FRB), consumed by
/// [`seal_and_persist`]. Held only for the ceremony and dropped — zeroizing the
/// phrase via the inner `Mnemonic`'s `Drop` — on seal, on [`abandon_create`], or
/// on the §0.11 lifecycle signal (via [`lock_vault`]). `None` = no create in
/// progress. A second strong owner beside `VAULT`: deliberate, not the L6
/// singleton anti-pattern — the native lane and FRB must observe one ceremony.
static CREATE_CEREMONY: Mutex<Option<MnemonicCeremony>> = Mutex::new(None);

const BLOB_FILE: &str = "vault.kvsb";
const LOCKOUT_FILE: &str = "vault.lockout";

// ── DTOs (FRB-facing: plain structs, no secret-shaped fields) ─────────────

/// What Dart may observe about the vault — bools and non-secret counters only.
#[derive(Clone, Debug, Default)]
pub struct VaultStatus {
    /// A sealed blob exists at rest (a wallet has been created).
    pub exists: bool,
    /// The vault is currently unlocked in memory.
    pub unlocked: bool,
    /// If rate-limited, the unix time (s) until which unlock is refused.
    pub locked_out_until_unix: Option<u64>,
    /// Consecutive failed unlock attempts (resets to 0 on any success).
    pub failed_attempts: u32,
}

/// Argon2id cost parameters chosen by on-device tuning (P1.2 §0.3). Mapped onto
/// the core `SealParams`, which bounds-checks them (8 MiB..=256 MiB, D-031.2).
#[derive(Clone, Copy, Debug)]
pub struct VaultKdfParams {
    pub m_cost_kib: u32,
    pub t_cost: u32,
    pub p_cost: u32,
}

impl VaultKdfParams {
    /// The v1 starting grid (P1 §0.3): m = 64 MiB, t = 3, p = 1. Kept for
    /// reference/benching; new vaults use [`VaultKdfParams::tuned`].
    pub fn starting_grid() -> Self {
        let d = SealParams::default();
        Self {
            m_cost_kib: d.m_cost_kib,
            t_cost: d.t_cost,
            p_cost: d.p_cost,
        }
    }

    /// The P1.2 on-device tuned point (LG V60, release build, 2026-06-13):
    /// m = 192 MiB → 679 ms measured, ~32% headroom under the ≤1.0 s unlock
    /// budget — 256 MiB measured 910 ms, too close to the edge for field
    /// thermal/load variance (D-026: a budget miss is a finding). Full grid
    /// in PERFORMANCE_BUDGET.md. Default for new vaults; the blob header
    /// carries whatever a vault was actually sealed with.
    pub fn tuned() -> Self {
        Self {
            m_cost_kib: 192 * 1024,
            t_cost: 3,
            p_cost: 1,
        }
    }
}

impl From<VaultKdfParams> for SealParams {
    fn from(p: VaultKdfParams) -> Self {
        SealParams {
            m_cost_kib: p.m_cost_kib,
            t_cost: p.t_cost,
            p_cost: p.p_cost,
        }
    }
}

// ── Lockout (persisted; survives process restart — wallet-security item 11) ─

/// After this many consecutive failures, backoff begins.
const LOCKOUT_FREE_ATTEMPTS: u32 = 5;

// Internal persistence type — NOT an FRB DTO. `frb(ignore)` keeps codegen from
// trying to marshal it to Dart (it would touch these private fields).
#[flutter_rust_bridge::frb(ignore)]
#[derive(Clone, Copy, Default, PartialEq, Eq, Debug)]
struct Lockout {
    failed_attempts: u32,
    locked_until_unix: u64,
}

impl Lockout {
    fn active_until(&self, now: u64) -> Option<u64> {
        (self.locked_until_unix > now).then_some(self.locked_until_unix)
    }

    fn to_bytes(self) -> [u8; 12] {
        let mut b = [0u8; 12];
        b[0..4].copy_from_slice(&self.failed_attempts.to_le_bytes());
        b[4..12].copy_from_slice(&self.locked_until_unix.to_le_bytes());
        b
    }

    fn from_bytes(b: &[u8]) -> Option<Self> {
        if b.len() != 12 {
            return None;
        }
        Some(Self {
            failed_attempts: u32::from_le_bytes([b[0], b[1], b[2], b[3]]),
            locked_until_unix: u64::from_le_bytes([
                b[4], b[5], b[6], b[7], b[8], b[9], b[10], b[11],
            ]),
        })
    }
}

/// Backoff after `failed` consecutive failures: 0 while under the free budget,
/// then 30 s doubling per extra failure, capped at one hour. Pure — unit-tested.
fn lockout_delay_secs(failed: u32) -> u64 {
    if failed <= LOCKOUT_FREE_ATTEMPTS {
        return 0;
    }
    let over = (failed - LOCKOUT_FREE_ATTEMPTS - 1).min(7);
    (30u64.saturating_mul(1u64 << over)).min(3600)
}

// ── Paths & time ──────────────────────────────────────────────────────────

fn vault_dir() -> Result<PathBuf, AppError> {
    VAULT_DIR
        .lock()
        .unwrap_or_else(PoisonError::into_inner)
        .clone()
        .ok_or_else(|| AppError::msg("vault not initialised — call init_vault first"))
}

fn blob_path() -> Result<PathBuf, AppError> {
    Ok(vault_dir()?.join(BLOB_FILE))
}

fn lockout_path() -> Result<PathBuf, AppError> {
    Ok(vault_dir()?.join(LOCKOUT_FILE))
}

/// App-private path for the wallet activity log (§0.10): the vault's dir, in a
/// `wallet/` subdir. Public chain data only (INV-3) — distinct from the sealed
/// blob, no encryption layer.
pub(crate) fn wallet_store_path() -> Result<PathBuf, AppError> {
    Ok(vault_dir()?.join("wallet").join("activity.kvlog"))
}

/// App-private path for the change-address cursor (P1.6, D-041): the next-unused
/// change index, persisted so fresh-per-send change survives a restart. Public
/// data (an index), in the same `wallet/` subdir — no encryption (INV-3).
pub(crate) fn change_cursor_path() -> Result<PathBuf, AppError> {
    Ok(vault_dir()?.join("wallet").join("change.cursor"))
}

/// App-private path remembering the last-good wRPC endpoint (P1.5 re-audit —
/// the connect fast path). Public data (a wss URL the PNN resolver handed us),
/// in the same `wallet/` subdir — no encryption (INV-3), no new trust (INV-8:
/// the resolver is already an untrusted accelerator; remembering its last
/// answer adds nothing).
pub(crate) fn endpoint_cache_path() -> Result<PathBuf, AppError> {
    Ok(vault_dir()?.join("wallet").join("endpoint.cache"))
}

/// App-private dir for the P2.3 transport stores (conversations + messages).
/// Message bodies in there are ciphertext-at-rest (§0.4); conversation
/// metadata is public-wire-class data (see `transport_store.rs` module docs)
/// — sibling of the P1.5 `wallet/` subdir.
pub(crate) fn transport_store_dir() -> Result<PathBuf, AppError> {
    Ok(vault_dir()?.join("transport"))
}

/// App-private dir for the V1 acceptance tracker (`acceptance.kvlog` +
/// `vcc.cursor`). Public chain data only — txids, block hashes, timestamps
/// (INV-3); node-only reads (INV-8). Sibling of `wallet/` and `transport/`;
/// serves BOTH (sends and conversation txids), hence its own home.
pub(crate) fn chain_store_dir() -> Result<PathBuf, AppError> {
    Ok(vault_dir()?.join("chain"))
}

/// A vault-scoped transport decryptor (core's weak-handle seam, P2.3): every
/// decrypt starts with a `Weak::upgrade` that fails once the vault locks —
/// key bytes exist only inside core, never here (INV-1). Errors if locked.
pub(crate) fn transport_decryptor() -> Result<kaspaverse_core::TransportDecryptor, AppError> {
    let guard = VAULT.lock().unwrap_or_else(PoisonError::into_inner);
    let vault = guard
        .as_ref()
        .ok_or_else(|| AppError::msg("wallet is locked"))?;
    Ok(vault.transport_decryptor())
}

/// The largest discovery mark this app can ever have written. A mark is
/// `highest_funded_index + 1`, and one pass probes at most
/// `wallet::MAX_DISCOVERY_DEPTH` indices, so a larger value on disk is not a
/// window we produced — it is corruption. (`wallet.rs` asserts that
/// relationship at compile time.)
pub(crate) const MAX_SCAN_MARK: u32 = 512;

/// The largest change cursor this app will believe — and therefore the largest
/// it will ever WRITE. Not a policy limit: the cursor advances by exactly one
/// per fully-broadcast send (D-041), so reaching it takes 100 000 sends from
/// this device.
///
/// The two must be the same number. A writer that can produce a value its own
/// reader rejects turns the 100 000th send into a cursor that reads back as
/// unset — silently dropping to the discovery mark and reusing change indices
/// the wallet already spent from. [`set_change_cursor`] refuses to pass it
/// instead, which repeats one index but says so.
pub(crate) const MAX_CHANGE_CURSOR: u32 = 100_000;

/// Validate a persisted count: **out of range reads as UNSET, never clamped.**
///
/// Both files are a handful of unauthenticated bytes on disk, and every consumer
/// scales linearly in their value — a window feeds `derive_wallet_addresses(n,
/// n)`, which is `Vec::with_capacity(n)` plus `n` BIP32 derivations under the
/// `VAULT` mutex. Unvalidated, `u32::MAX` is a ~137 GB allocation →
/// `handle_alloc_error` → **SIGABRT**, worse than the caught panic INV-2
/// forbids and self-reinforcing, since the same bytes are re-read every launch.
///
/// Clamping to the ceiling stops the abort and replaces it with something almost
/// as bad: the widest legal window forever, on every unlock and every send,
/// never rewritten — the marks only persist when they *change*, so the corrupt
/// bytes survive, and the only user escape (clear app data) destroys
/// `vault.kvsb`. Zero is the honest reading of a value this app could not have
/// written, and it heals: discovery re-probes and writes a sane mark, the next
/// send writes a sane cursor. Neither loses funds — the window is rebuilt from
/// the chain, and `wallet::next_change_index` floors the cursor at the
/// discovered mark, so a cursor read as 0 still lands past the funded history.
fn persisted_count(raw: u32, ceiling: u32) -> u32 {
    if raw > ceiling {
        log::warn!("vault: persisted count {raw} is past its {ceiling} ceiling — reading as unset");
        return 0;
    }
    raw
}

/// Read the persisted change cursor (the next-unused change index). A missing,
/// malformed or out-of-range file reads as 0 — a fresh wallet has used no change
/// addresses, and an impossible one is not evidence (see [`persisted_count`]).
pub(crate) fn change_cursor() -> u32 {
    let raw = change_cursor_path()
        .ok()
        .and_then(|p| fs::read(p).ok())
        .filter(|b| b.len() == 4)
        .map(|b| u32::from_le_bytes([b[0], b[1], b[2], b[3]]))
        .unwrap_or(0);
    persisted_count(raw, MAX_CHANGE_CURSOR)
}

/// Persist the change cursor atomically — advanced only after a fully-broadcast
/// send (D-041), so an abandoned/failed send never burns an index.
///
/// Refuses to write past [`MAX_CHANGE_CURSOR`], so the file can never hold a
/// value [`change_cursor`] reads as unset. Reaching that is 100 000 sends from
/// one device; past it, change addresses repeat from the last index, which is a
/// linkability regression stated in the log rather than a silent fall back to
/// indices the wallet's own history already spent from.
pub(crate) fn set_change_cursor(next: u32) -> Result<(), AppError> {
    if next > MAX_CHANGE_CURSOR {
        log::warn!(
            "vault: change cursor is at its {MAX_CHANGE_CURSOR} ceiling — not advancing; \
             change addresses repeat from here (D-041 fresh-per-send no longer holds)"
        );
        return Ok(());
    }
    atomic_write(&change_cursor_path()?, &next.to_le_bytes())
        .map_err(|e| AppError::io("write change cursor", e))
}

/// App-private path for the discovery high-water marks: the highest FUNDED
/// receive and change index observed on chain. Public data (two indices), same
/// `wallet/` subdir, no encryption (INV-3).
pub(crate) fn scan_window_path() -> Result<PathBuf, AppError> {
    Ok(vault_dir()?.join("wallet").join("scan.window"))
}

/// Read the persisted `(receive_seen, change_seen)` discovery marks — COUNTS of
/// indices needing coverage (`highest_funded + 1`), never bare indices, so that 0
/// means "nothing found" and cannot be confused with "index 0 is funded".
/// Missing or
/// malformed reads as `(0, 0)` — nothing discovered yet, so the caller falls
/// back to the fixed gap limit.
///
/// **Deliberately not `change.cursor`.** That file counts change indices *this
/// app* burned on its own sends (D-041); it is written only after a successful
/// broadcast and knows nothing about a wallet used elsewhere. Conflating the two
/// is precisely what let a restored wallet watch 30 addresses while its funds
/// sat at change index 77 — a local send-counter was standing in for a fact
/// about the chain. Two files, two meanings, neither pretending to be the other.
///
/// Each mark is validated by [`persisted_count`] against [`MAX_SCAN_MARK`] and
/// OR-ed with what this process has already learned (see
/// [`set_scan_high_water`]), so the window never depends on a disk write having
/// succeeded.
pub(crate) fn scan_high_water() -> (u32, u32) {
    let (disk_receive, disk_change) = scan_window_path()
        .ok()
        .and_then(|p| fs::read(p).ok())
        .filter(|b| b.len() == 8)
        .map(|b| {
            (
                persisted_count(u32::from_le_bytes([b[0], b[1], b[2], b[3]]), MAX_SCAN_MARK),
                persisted_count(u32::from_le_bytes([b[4], b[5], b[6], b[7]]), MAX_SCAN_MARK),
            )
        })
        .unwrap_or((0, 0));
    // The memo goes through the same validation as the disk half — one
    // validation point that covers only one of two inputs is not one.
    let (memo_receive, memo_change) = SCAN_MARKS
        .lock()
        .unwrap_or_else(PoisonError::into_inner)
        .map(|(r, c)| {
            (
                persisted_count(r, MAX_SCAN_MARK),
                persisted_count(c, MAX_SCAN_MARK),
            )
        })
        .unwrap_or((0, 0));
    (disk_receive.max(memo_receive), disk_change.max(memo_change))
}

/// What a discovery pass has learned **this process**, whether or not the write
/// to disk stuck. Held because the failure is otherwise silent and expensive: a
/// successful probe followed by a failed persist used to leave the caller
/// re-reading the OLD marks off disk and opening on the narrow window — the
/// exact stranding this whole mechanism exists to prevent — for a wallet that
/// had just proved where its funds were. A failed write now costs the NEXT
/// launch one re-probe and costs this session nothing.
///
/// Monotonic and process-lifetime — it survives a vault lock on purpose (see
/// [`lock_vault`]); only the test harness resets it, because tests fabricate
/// several fresh vault dirs inside one process.
static SCAN_MARKS: Mutex<Option<(u32, u32)>> = Mutex::new(None);

/// Record the discovery marks — in memory first, then to disk.
///
/// Monotonic in BOTH stores, structurally: the max is taken once and the same
/// values go to memory and to disk. Persisting the caller's raw arguments while
/// max-ing only the memo would leave on-disk monotonicity resting on the one
/// call site that happens to compute it correctly — and a future second caller
/// narrowing the marks means the next launch opens on the narrow window, which
/// is the original defect. A scan that finds nothing must never shrink a window
/// that previously found something, or a transient RPC failure would strand
/// funds we had already learned to watch.
pub(crate) fn set_scan_high_water(receive_hi: u32, change_hi: u32) -> Result<(), AppError> {
    let (receive_hi, change_hi) = {
        let mut memo = SCAN_MARKS.lock().unwrap_or_else(PoisonError::into_inner);
        let (prev_receive, prev_change) = memo.unwrap_or((0, 0));
        let grown = (prev_receive.max(receive_hi), prev_change.max(change_hi));
        *memo = Some(grown);
        grown
    };
    let mut bytes = [0u8; 8];
    bytes[..4].copy_from_slice(&receive_hi.to_le_bytes());
    bytes[4..].copy_from_slice(&change_hi.to_le_bytes());
    atomic_write(&scan_window_path()?, &bytes).map_err(|e| AppError::io("write scan window", e))
}

/// Derive the public receive + change address window from the unlocked vault,
/// for the wallet-sync engine. INV-1: the seed and the `KeyChain` NEVER leave
/// this module — the keychain reference is held only under the `VAULT` lock and
/// only public [`Address`] values are returned. The single derivation site (the
/// two-consumer seam, now wired): the SAME window is watched by the `UtxoContext`
/// (via the engine) and registered with the `VaultSigner` ([`build_wallet_signer`]).
/// `change_count` widens with the change cursor (D-041) so used change addresses
/// are re-watched after a restart. Errors if locked.
/// Returns `(all_watched, change_only)`: the full receive+change window to watch,
/// and — separately — the change addresses, so the sync engine can tell our own
/// returning change from a real deposit (a UTXO at a change address is never a
/// deposit; D — device find 2026-06-15).
pub(crate) fn derive_wallet_addresses(
    receive_count: u32,
    change_count: u32,
) -> Result<(Vec<Address>, Vec<Address>), AppError> {
    let (receive, change) = derive_wallet_branches(receive_count, change_count)?;
    let all = receive.into_iter().chain(change.iter().cloned()).collect();
    Ok((all, change))
}

/// The same single derivation site, returning the branches **separately** as
/// `(receive, change)`.
///
/// Exists because address discovery needs the receive branch on its own, and
/// taking it as `&all[..receive_count]` made a cross-module layout contract —
/// "the concatenation is receive-then-change" — load-bearing with nothing but a
/// comment holding it. Correct today and unable to panic, but if that order ever
/// flipped, discovery would read change balances as receive indices and the
/// window would widen on the wrong branch. A tuple cannot be misread.
pub(crate) fn derive_wallet_branches(
    receive_count: u32,
    change_count: u32,
) -> Result<(Vec<Address>, Vec<Address>), AppError> {
    let guard = VAULT.lock().unwrap_or_else(PoisonError::into_inner);
    let vault = guard
        .as_ref()
        .ok_or_else(|| AppError::msg("wallet is locked — cannot derive addresses"))?;
    let keychain = vault.keychain();
    let mut receive = Vec::with_capacity(receive_count as usize);
    for index in 0..receive_count {
        receive.push(keychain.receive_address(index).map_err(AppError::core)?);
    }
    let mut change = Vec::with_capacity(change_count as usize);
    for index in 0..change_count {
        change.push(keychain.change_address(index).map_err(AppError::core)?);
    }
    Ok((receive, change))
}

/// The change address at `index` (public — derived from the account xpub), for a
/// send's fresh change (P1.6, D-041). Same single derivation site; the keychain
/// never leaves this module (INV-1). Errors if locked.
pub(crate) fn change_address_at(index: u32) -> Result<Address, AppError> {
    let guard = VAULT.lock().unwrap_or_else(PoisonError::into_inner);
    let vault = guard
        .as_ref()
        .ok_or_else(|| AppError::msg("wallet is locked"))?;
    vault
        .keychain()
        .change_address(index)
        .map_err(AppError::core)
}

/// The watched-window address at an arbitrary `(branch, index)` slot — the
/// P2.3 re-seal-to-self target (a conversation's §0.7 bound slot). Public
/// data, same single derivation site. Errors if locked.
pub(crate) fn wallet_address_at(branch: Branch, index: u32) -> Result<Address, AppError> {
    let guard = VAULT.lock().unwrap_or_else(PoisonError::into_inner);
    let vault = guard
        .as_ref()
        .ok_or_else(|| AppError::msg("wallet is locked"))?;
    vault
        .keychain()
        .address(branch, index)
        .map_err(AppError::core)
}

/// Build a [`VaultSigner`] for a send, registering the SAME watched window
/// (receive `0..receive_count` + change `0..change_count`) so `try_sign` resolves
/// any input the Generator selects, plus the fresh change. The signer holds a
/// Weak ref to the keychain (the lock kill switch); keys are derived transiently
/// per signature and zeroized (signer.rs). INV-1: the keychain stays inside this
/// module — only the opaque signer (no key table in memory) leaves. Errors if locked.
pub(crate) fn build_wallet_signer(
    receive_count: u32,
    change_count: u32,
) -> Result<VaultSigner, AppError> {
    let guard = VAULT.lock().unwrap_or_else(PoisonError::into_inner);
    let vault = guard
        .as_ref()
        .ok_or_else(|| AppError::msg("wallet is locked — cannot sign"))?;
    let signer = vault.signer();
    for index in 0..receive_count {
        signer
            .register(Branch::Receive, index)
            .map_err(AppError::core)?;
    }
    for index in 0..change_count {
        signer
            .register(Branch::Change, index)
            .map_err(AppError::core)?;
    }
    Ok(signer)
}

/// The wallet's primary receive address (receive index 0), for the Receive
/// sheet. An address is PUBLIC (derived from the account xpub) — INV-1 governs
/// secrets, not addresses — so it may cross the FFI. Errors if the vault is
/// locked. (Next-unused-address rotation is deferred; P1.5 shows index 0.)
pub fn vault_receive_address() -> Result<String, AppError> {
    let guard = VAULT.lock().unwrap_or_else(PoisonError::into_inner);
    let vault = guard
        .as_ref()
        .ok_or_else(|| AppError::msg("wallet is locked"))?;
    let address: String = vault
        .keychain()
        .receive_address(0)
        .map_err(AppError::core)?
        .into();
    Ok(address)
}

fn now_unix() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

// ── Atomic storage (temp + fsync + rename; power-cut-safe) ────────────────

/// Write `bytes` to `path` atomically: a power cut mid-write leaves the old
/// file intact, never a half-written one (P1.1-audit corruption vector). Temp
/// file in the SAME directory → fsync data → rename (atomic on POSIX) → fsync
/// the directory so the rename itself is durable. std-only (no new dep).
/// `pub(crate)` so the wallet/send lanes reuse it (the change cursor, P1.6).
pub(crate) fn atomic_write(path: &Path, bytes: &[u8]) -> io::Result<()> {
    let dir = path
        .parent()
        .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "path has no parent dir"))?;
    let name = path
        .file_name()
        .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "path has no file name"))?;
    // Create the parent on the way in. `scan.window` is the first writer into
    // `wallet/` on a fresh install, and the failure it used to produce was
    // silent in the worst possible way: the write errors, the caller reads it as
    // "discovery failed", and the wallet opens on the 30-wide window — on
    // exactly the restored wallet the mark exists for.
    fs::create_dir_all(dir)?;
    let tmp = dir.join(format!(".{}.tmp", name.to_string_lossy()));
    {
        let mut f = fs::File::create(&tmp)?;
        f.write_all(bytes)?;
        f.sync_all()?; // data on disk before the rename
    }
    fs::rename(&tmp, path)?; // atomic replace within the directory
                             // Best-effort directory fsync: makes the rename survive a power cut.
                             // The rename's atomicity does not depend on it (it can't tear).
    if let Ok(dirf) = fs::File::open(dir) {
        let _ = dirf.sync_all();
    }
    Ok(())
}

fn read_lockout() -> Lockout {
    lockout_path()
        .ok()
        .and_then(|p| fs::read(p).ok())
        .and_then(|b| Lockout::from_bytes(&b))
        .unwrap_or_default()
}

fn write_lockout(l: Lockout) -> Result<(), AppError> {
    atomic_write(&lockout_path()?, &l.to_bytes()).map_err(|e| AppError::io("write lockout", e))
}

// ── Status ────────────────────────────────────────────────────────────────

fn is_unlocked() -> bool {
    VAULT
        .lock()
        .unwrap_or_else(PoisonError::into_inner)
        .is_some()
}

fn current_status() -> VaultStatus {
    let lockout = read_lockout();
    VaultStatus {
        exists: blob_path().map(|p| p.exists()).unwrap_or(false),
        unlocked: is_unlocked(),
        locked_out_until_unix: lockout.active_until(now_unix()),
        failed_attempts: lockout.failed_attempts,
    }
}

fn status_tx() -> &'static broadcast::Sender<VaultStatus> {
    STATUS_TX.get_or_init(|| broadcast::channel(16).0)
}

fn broadcast_status() {
    let _ = status_tx().send(current_status()); // fails only with no subscribers
}

fn set_vault(v: UnlockedVault) {
    *VAULT.lock().unwrap_or_else(PoisonError::into_inner) = Some(v);
}

// ── FRB surface ───────────────────────────────────────────────────────────

/// Hand the bridge the platform's app-private directory (INV-3). Idempotent
/// for the same path (hot restart re-calls it); a later call with a DIFFERENT
/// path is refused — silently re-homing the vault would strand the blob and
/// the lockout state where no caller looks (custody, not configuration).
pub fn init_vault(app_private_dir: String) -> Result<(), AppError> {
    let new = PathBuf::from(app_private_dir);
    let mut dir = VAULT_DIR.lock().unwrap_or_else(PoisonError::into_inner);
    match dir.as_ref() {
        Some(current) if *current != new => {
            return Err(AppError::msg(
                "vault dir already initialised to a different path; refusing to re-home",
            ));
        }
        _ => *dir = Some(new),
    }
    drop(dir);
    broadcast_status();
    Ok(())
}

/// Subscribe to vault status. Paints the current state immediately, then on
/// every change. One stream per process; survives Dart hot restart (re-attach).
pub async fn vault_status_stream(sink: StreamSink<VaultStatus>) -> Result<(), AppError> {
    let mut rx = status_tx().subscribe();
    let _ = sink.add(current_status());
    tokio::spawn(async move {
        loop {
            match rx.recv().await {
                Ok(s) => {
                    if sink.add(s).is_err() {
                        break;
                    }
                }
                Err(RecvError::Lagged(_)) => continue,
                Err(RecvError::Closed) => break,
            }
        }
    });
    Ok(())
}

/// Whether a sealed blob exists at rest.
pub fn vault_exists() -> bool {
    blob_path().map(|p| p.exists()).unwrap_or(false)
}

// ── P1.4 create ceremony (two-step: generate → hold → reveal → seal) ────────
// D-038, debt repaid at the P1.4 device pass. The retired `create_vault` (a
// one-shot generate+seal that never surfaced the phrase, so it could not back a
// real backup) is GONE — these two-step fns ARE the onboarding surface. The live
// phrase is held in `CREATE_CEREMONY` and shown only by the native reveal/verify
// surface over the JNI lane (D-037) — never FRB.

/// Begin a create ceremony: generate a fresh 12-word mnemonic and hold it for
/// the native reveal/verify surface. Refuses if a vault already exists (one
/// wallet per install) or a ceremony is already in progress (seal or abandon the
/// prior one first). The phrase never crosses FRB.
pub fn begin_create() -> Result<(), AppError> {
    if blob_path()?.exists() {
        return Err(AppError::msg(
            "a vault already exists; refusing to overwrite",
        ));
    }
    let mut slot = CREATE_CEREMONY
        .lock()
        .unwrap_or_else(PoisonError::into_inner);
    if slot.is_some() {
        return Err(AppError::msg("a create ceremony is already in progress"));
    }
    *slot = Some(MnemonicCeremony::generate().map_err(AppError::core)?);
    log::info!("create ceremony begun (12 words held; no secret values)");
    Ok(())
}

/// Abandon an in-progress create ceremony (back-gesture / cancel): drops the
/// held mnemonic, zeroizing the phrase. Idempotent (a no-op if none is held).
pub fn abandon_create() {
    if CREATE_CEREMONY
        .lock()
        .unwrap_or_else(PoisonError::into_inner)
        .take()
        .is_some()
    {
        log::info!("create ceremony abandoned");
    }
}

/// Complete a create ceremony: seal the held mnemonic's seed under `passphrase`,
/// persist the blob atomically, and leave the vault unlocked. The optional
/// `extra_word` (13th word / BIP39 passphrase) is restricted to **ASCII** on the
/// create path (D-031.5; `mnemonic.rs::into_seed`): the pinned `to_seed` does no
/// NFKD, so a non-ASCII extra word would silently derive a different wallet on a
/// normalizing implementation — refused here so a NEW backup stays portable. The
/// cheap checks (ASCII, vault-absent, ceremony-present) run BEFORE the ceremony
/// is consumed, so a rejected attempt leaves it held for a retry.
pub fn seal_and_persist(
    passphrase: Vec<u8>,
    extra_word: Vec<u8>,
    params: VaultKdfParams,
) -> Result<(), AppError> {
    let passphrase = Zeroizing::new(passphrase);
    let extra_word = Zeroizing::new(extra_word);
    if !extra_word.is_ascii() {
        return Err(AppError::msg(
            "extra word must be ASCII — a non-ASCII word can derive a different wallet elsewhere",
        ));
    }
    if blob_path()?.exists() {
        return Err(AppError::msg(
            "a vault already exists; refusing to overwrite",
        ));
    }
    let ceremony = CREATE_CEREMONY
        .lock()
        .unwrap_or_else(PoisonError::into_inner)
        .take()
        .ok_or_else(|| AppError::msg("no create ceremony in progress"))?;
    let seed = ceremony.into_seed(&extra_word).map_err(AppError::core)?;
    let blob = seal_seed(&seed, &passphrase, params.into()).map_err(AppError::core)?;
    atomic_write(&blob_path()?, &blob).map_err(|e| AppError::io("write blob", e))?;
    set_vault(UnlockedVault::new(
        KeyChain::from_seed(seed, Prefix::Mainnet).map_err(AppError::core)?,
    ));
    log::info!("vault created (path=passphrase scheme=argon2id, ceremony-backed)");
    broadcast_status();
    Ok(())
}

/// Restore preview (deliverable 2 — the decoy/typo trap): derive the FIRST
/// receive address from a candidate phrase WITHOUT persisting or unlocking. A
/// single wrong word opens a visibly DIFFERENT wallet, so surfacing the derived
/// address lets the user catch a typo before committing instead of landing in a
/// silent empty wallet. The address is public (INV-2 permits it to cross);
/// `phrase`/`extra_word` are the user's `Uint8List`, wiped Dart-side after the
/// call (INV-1 sentence two). Restore accepts any UTF-8 extra word (max
/// compatibility — unlike the ASCII-only create path).
pub fn restore_preview(phrase: Vec<u8>, extra_word: Vec<u8>) -> Result<String, AppError> {
    let phrase = Zeroizing::new(phrase);
    let extra_word = Zeroizing::new(extra_word);
    let seed = MnemonicCeremony::restore(&phrase)
        .map_err(AppError::core)?
        .into_seed(&extra_word)
        .map_err(AppError::core)?;
    let keychain = KeyChain::from_seed(seed, Prefix::Mainnet).map_err(AppError::core)?;
    let address: String = keychain.receive_address(0).map_err(AppError::core)?.into();
    Ok(address)
}

/// Restore-commit (deliverable 2): restore from `phrase` (+ optional
/// `extra_word`), seal the derived seed under `passphrase`, persist, unlock.
/// Refuses if a vault already exists. Any-UTF-8 extra word (restore is the
/// compatibility path; the ASCII restriction is create-only).
pub fn restore_and_persist(
    phrase: Vec<u8>,
    extra_word: Vec<u8>,
    passphrase: Vec<u8>,
    params: VaultKdfParams,
) -> Result<(), AppError> {
    let phrase = Zeroizing::new(phrase);
    let extra_word = Zeroizing::new(extra_word);
    let passphrase = Zeroizing::new(passphrase);
    if blob_path()?.exists() {
        return Err(AppError::msg(
            "a vault already exists; refusing to overwrite",
        ));
    }
    let seed = MnemonicCeremony::restore(&phrase)
        .map_err(AppError::core)?
        .into_seed(&extra_word)
        .map_err(AppError::core)?;
    let blob = seal_seed(&seed, &passphrase, params.into()).map_err(AppError::core)?;
    atomic_write(&blob_path()?, &blob).map_err(|e| AppError::io("write blob", e))?;
    set_vault(UnlockedVault::new(
        KeyChain::from_seed(seed, Prefix::Mainnet).map_err(AppError::core)?,
    ));
    log::info!("vault restored (path=passphrase scheme=argon2id)");
    broadcast_status();
    Ok(())
}

/// Serializes passphrase-unlock attempts end-to-end. The lockout counter is a
/// read-modify-write spanning a seconds-long KDF — unserialized, concurrent
/// failures lose updates (caught LIVE on-device 2026-06-13: two overlapping
/// wrong attempts both recorded `attempt=1`, so a burst of N parallel guesses
/// would count as one — wallet-security item 11). Concurrent attempts have no
/// legitimate use; they wait their turn.
static UNLOCK_GATE: Mutex<()> = Mutex::new(());

/// Unlock via passphrase (Path B). Rate-limit is checked BEFORE the KDF runs
/// (wallet-security 11), so a locked-out attempt costs nothing. On failure the
/// attempt counter advances and persists; on success it resets. Attempts are
/// serialized by [`UNLOCK_GATE`] so every failure is counted.
pub fn unlock_with_passphrase(passphrase: Vec<u8>) -> Result<(), AppError> {
    let _gate = UNLOCK_GATE.lock().unwrap_or_else(PoisonError::into_inner);
    let passphrase = Zeroizing::new(passphrase);
    let now = now_unix();
    let mut lockout = read_lockout();
    if let Some(until) = lockout.active_until(now) {
        let remaining = until.saturating_sub(now);
        log::warn!("vault unlock refused: locked out {remaining}s");
        return Err(AppError::msg(format!(
            "too many attempts — locked out for {remaining} more seconds"
        )));
    }
    log::info!("vault unlock attempt (path=passphrase)");
    let blob = read_blob()?;
    match unseal_seed(&blob, &passphrase) {
        Ok(seed) => {
            let keychain = KeyChain::from_seed(seed, Prefix::Mainnet).map_err(AppError::core)?;
            set_vault(UnlockedVault::new(keychain));
            let _ = write_lockout(Lockout::default()); // reset on success
            log::info!("vault unlock ok (path=passphrase)");
            broadcast_status();
            Ok(())
        }
        Err(e) => {
            lockout.failed_attempts = lockout.failed_attempts.saturating_add(1);
            let delay = lockout_delay_secs(lockout.failed_attempts);
            if delay > 0 {
                lockout.locked_until_unix = now.saturating_add(delay);
            }
            let _ = write_lockout(lockout);
            log::warn!(
                "vault unlock failed (path=passphrase, attempt={})",
                lockout.failed_attempts
            );
            broadcast_status();
            Err(AppError::core(e))
        }
    }
}

/// Lock the vault. **Contract (D-031.4): "no new operation can start", not
/// "instant erasure".** A sign already in flight holds an upgraded strong ref
/// (from the core Arc/Weak design) and completes; the seed zeroizes when that
/// last ref drops. This fn intentionally exposes no "erased" flag — `VaultStatus`
/// reports `unlocked=false` only — so the bridge can never assert erasure while
/// a sign is concurrently finishing. Also the Flutter lifecycle hook: Dart calls
/// this on background/detach.
pub fn lock_vault() {
    if let Some(vault) = VAULT.lock().unwrap_or_else(PoisonError::into_inner).take() {
        vault.lock(); // consumes; drops the bridge's strong Arc
        log::info!("vault locked");
    }
    // §0.11: a background/detach mid-create must not leave the phrase resident.
    // Dropping the held ceremony zeroizes it (D-038); abandon is idempotent.
    if CREATE_CEREMONY
        .lock()
        .unwrap_or_else(PoisonError::into_inner)
        .take()
        .is_some()
    {
        log::info!("create ceremony dropped (lifecycle)");
    }
    // NOTE: `SCAN_MARKS` deliberately survives a lock. It is tempting to clear
    // it as "vault state", and that would be a real bug: if the persist to disk
    // had failed, clearing the memo makes the re-unlock read `(0, 0)` and
    // rebuild the SIGNER on a 30-wide window — while the sync engine, which is
    // process-lifetime and untouched by a lock, keeps watching the wide one.
    // Visible and unspendable, which is the exact state this whole mechanism
    // exists to prevent. The memo only ever grows, and there is one wallet per
    // install, so keeping it can only widen.
    broadcast_status();
}

fn read_blob() -> Result<Vec<u8>, AppError> {
    fs::read(blob_path()?).map_err(|e| AppError::io("read blob", e))
}

/// Time one Argon2id run at `params` on THIS device (P1.2 §0.3 tuning):
/// seals a throwaway seed under a dummy passphrase and returns elapsed
/// milliseconds. No secrets involved; bounds-checked by the core
/// (8 MiB..=256 MiB, D-031.2). Runs on FRB's worker pool like the real KDF.
pub fn kdf_bench_ms(params: VaultKdfParams) -> Result<u64, AppError> {
    let seed = SecretSeed::from_seed_bytes(Box::new([0u8; 64]));
    let started = std::time::Instant::now();
    seal_seed(&seed, b"kdf-bench-dummy", params.into()).map_err(AppError::core)?;
    Ok(started.elapsed().as_millis() as u64)
}

// ── JNI lane entry points (called by `jni_seed`, Android-only) ────────────
// Not `pub`, so FRB never exposes them to Dart — they are the Kotlin↔Rust
// seed lane only.

/// Path-A unlock: load the vault from the raw seed bytes the Keystore Cipher
/// decrypted (delivered over JNI). A biometric unlock is a success like a
/// passphrase one, so it resets the lockout.
#[cfg_attr(not(target_os = "android"), allow(dead_code))]
pub(crate) fn load_vault_from_seed_bytes(seed: Box<[u8; 64]>) -> Result<(), AppError> {
    let keychain = KeyChain::from_seed(SecretSeed::from_seed_bytes(seed), Prefix::Mainnet)
        .map_err(AppError::core)?;
    set_vault(UnlockedVault::new(keychain));
    let _ = write_lockout(Lockout::default());
    log::info!("vault unlock ok (path=biometric)");
    broadcast_status();
    Ok(())
}

/// Path-A enroll: hand the live seed to the JNI export so the Keystore Cipher
/// can wrap it under a hardware key. Errors if locked. The returned buffer
/// zeroizes on drop — the JNI side copies it into a Java `byte[]` and drops it.
#[cfg_attr(not(target_os = "android"), allow(dead_code))]
pub(crate) fn export_seed_for_keystore() -> Result<Zeroizing<[u8; 64]>, AppError> {
    let guard = VAULT.lock().unwrap_or_else(PoisonError::into_inner);
    let vault = guard
        .as_ref()
        .ok_or_else(|| AppError::msg("vault is locked; cannot export seed for sealing"))?;
    Ok(vault.with_seed_bytes(|b| Zeroizing::new(*b)))
}

/// Reveal lane (P1.4, D-037): the space-joined words of the in-progress create
/// ceremony, for the native FLAG_SECURE reveal/verify surface to render. The
/// returned buffer zeroizes on drop; the JNI side copies it into a Java `byte[]`,
/// renders, and wipes it (the same JVM residual class as Path-A enroll, D-033).
/// Pre-sized so the join never reallocates (no stray heap fragments). Errors if
/// no ceremony is in progress. Words NEVER cross FRB (INV-1) — only this
/// crate-internal JNI path reads them.
#[cfg_attr(not(target_os = "android"), allow(dead_code))]
pub(crate) fn reveal_ceremony_words() -> Result<Zeroizing<Vec<u8>>, AppError> {
    let guard = CREATE_CEREMONY
        .lock()
        .unwrap_or_else(PoisonError::into_inner);
    let ceremony = guard
        .as_ref()
        .ok_or_else(|| AppError::msg("no create ceremony in progress"))?;
    // 24 words × ~8 bytes + separators sits well under 256; no reallocation.
    let mut buf: Zeroizing<Vec<u8>> = Zeroizing::new(Vec::with_capacity(256));
    for (i, word) in ceremony.words().enumerate() {
        if i > 0 {
            buf.push(b' ');
        }
        buf.extend_from_slice(word.as_bytes());
    }
    Ok(buf)
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU64, Ordering};

    // Serializes every test that touches the process-wide VAULT/VAULT_DIR so
    // cargo's default parallel runner can't let them clobber each other (L7).
    static TEST_LOCK: Mutex<()> = Mutex::new(());
    static COUNTER: AtomicU64 = AtomicU64::new(0);

    // Fast, in-bounds KDF so the suite stays quick (mirrors core's TEST_PARAMS).
    pub(crate) fn cheap_params() -> VaultKdfParams {
        VaultKdfParams {
            m_cost_kib: 8 * 1024,
            t_cost: 1,
            p_cost: 1,
        }
    }

    fn fresh_dir() -> PathBuf {
        let mut p = std::env::temp_dir();
        p.push(format!(
            "kv-vault-test-{}-{}",
            std::process::id(),
            COUNTER.fetch_add(1, Ordering::Relaxed)
        ));
        fs::create_dir_all(&p).unwrap();
        p
    }

    /// Enter a clean global-vault world: lock the serializer, point VAULT_DIR
    /// at a fresh temp dir, clear any leftover unlocked vault. Returns the guard
    /// (held for the test's lifetime) and the dir.
    pub(crate) fn enter() -> (std::sync::MutexGuard<'static, ()>, PathBuf) {
        let guard = TEST_LOCK.lock().unwrap_or_else(PoisonError::into_inner);
        let dir = fresh_dir();
        *VAULT_DIR.lock().unwrap_or_else(PoisonError::into_inner) = Some(dir.clone());
        *VAULT.lock().unwrap_or_else(PoisonError::into_inner) = None;
        *CREATE_CEREMONY
            .lock()
            .unwrap_or_else(PoisonError::into_inner) = None;
        // The discovery memo outlives a temp dir (it is process state, not
        // vault state), so a test that widened the window would otherwise hand
        // the next test a wallet that had already found funds.
        *SCAN_MARKS.lock().unwrap_or_else(PoisonError::into_inner) = None;
        (guard, dir)
    }

    // ── Pure-logic tests (no global state) ────────────────────────────────

    #[test]
    fn lockout_backoff_is_zero_under_budget_then_grows_and_caps() {
        for n in 0..=LOCKOUT_FREE_ATTEMPTS {
            assert_eq!(lockout_delay_secs(n), 0, "no lockout at {n} failures");
        }
        assert_eq!(lockout_delay_secs(LOCKOUT_FREE_ATTEMPTS + 1), 30);
        assert_eq!(lockout_delay_secs(LOCKOUT_FREE_ATTEMPTS + 2), 60);
        assert_eq!(lockout_delay_secs(LOCKOUT_FREE_ATTEMPTS + 3), 120);
        // Caps at one hour, never overflows however many failures.
        assert_eq!(lockout_delay_secs(100), 3600);
        assert_eq!(lockout_delay_secs(u32::MAX), 3600);
    }

    #[test]
    fn lockout_serialises_round_trip_and_rejects_wrong_length() {
        let l = Lockout {
            failed_attempts: 7,
            locked_until_unix: 1_700_000_123,
        };
        assert_eq!(Lockout::from_bytes(&l.to_bytes()), Some(l));
        assert_eq!(Lockout::from_bytes(&[0u8; 11]), None);
        assert_eq!(Lockout::from_bytes(&[]), None);
    }

    #[test]
    fn the_cursor_never_writes_a_value_its_own_reader_would_reject() {
        let (_g, _dir) = enter();
        // The writer's whole range round-trips.
        for value in [0u32, 1, 77, MAX_CHANGE_CURSOR - 1, MAX_CHANGE_CURSOR] {
            set_change_cursor(value).unwrap();
            assert_eq!(change_cursor(), value);
        }
        // And past the ceiling it holds rather than writing something that
        // reads back as unset — which would drop the next send to the discovery
        // mark and reuse indices the wallet already spent from.
        set_change_cursor(MAX_CHANGE_CURSOR + 1).unwrap();
        assert_eq!(change_cursor(), MAX_CHANGE_CURSOR);
        set_change_cursor(u32::MAX).unwrap();
        assert_eq!(change_cursor(), MAX_CHANGE_CURSOR);
    }

    #[test]
    fn an_impossible_persisted_count_reads_as_unset_never_as_the_ceiling() {
        // In range, including the boundary, passes through untouched.
        assert_eq!(persisted_count(0, MAX_SCAN_MARK), 0);
        assert_eq!(persisted_count(78, MAX_SCAN_MARK), 78);
        assert_eq!(persisted_count(MAX_SCAN_MARK, MAX_SCAN_MARK), MAX_SCAN_MARK);

        // Out of range is UNSET, not clamped — the distinction the second
        // wallet-security audit turned on. Clamping stops the SIGABRT and
        // replaces it with a permanent brick: the widest legal window on every
        // unlock and every send, and the bad bytes are never rewritten, because
        // the marks only persist when they change. Zero re-probes and heals.
        assert_eq!(persisted_count(MAX_SCAN_MARK + 1, MAX_SCAN_MARK), 0);
        assert_eq!(persisted_count(u32::MAX, MAX_SCAN_MARK), 0);
        assert_eq!(persisted_count(u32::MAX, MAX_CHANGE_CURSOR), 0);
    }

    #[test]
    fn the_scan_marks_are_monotonic_on_disk_and_not_only_in_memory() {
        let (_g, _dir) = enter();
        set_scan_high_water(41, 78).unwrap();
        assert_eq!(scan_high_water(), (41, 78));

        // A caller passing something smaller must not narrow either store. The
        // memo would have absorbed it either way; this asserts the FILE did too,
        // because a next launch reads the file and nothing else.
        set_scan_high_water(0, 12).unwrap();
        let bytes = fs::read(scan_window_path().unwrap()).unwrap();
        assert_eq!(
            (
                u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]),
                u32::from_le_bytes([bytes[4], bytes[5], bytes[6], bytes[7]]),
            ),
            (41, 78),
            "the persisted marks narrowed — the next launch would open short"
        );
        assert_eq!(scan_high_water(), (41, 78));
    }

    #[test]
    fn a_corrupt_scan_window_file_reads_as_unset_and_the_next_pass_heals_it() {
        let (_g, _dir) = enter();
        let path = scan_window_path().unwrap();
        atomic_write(&path, &[0xffu8; 8]).unwrap();
        assert_eq!(
            scan_high_water(),
            (0, 0),
            "an impossible mark is not evidence"
        );
        // …and the wallet is not stuck there: a real pass writes over it.
        set_scan_high_water(3, 78).unwrap();
        assert_eq!(scan_high_water(), (3, 78));
    }

    #[test]
    fn atomic_write_replaces_without_tearing_and_makes_dirs_durable() {
        let dir = fresh_dir();
        let path = dir.join("blob.bin");
        atomic_write(&path, b"first-version").unwrap();
        assert_eq!(fs::read(&path).unwrap(), b"first-version");
        // Overwrite with a different length — old content fully replaced, and
        // no stray temp file left behind.
        atomic_write(&path, b"second").unwrap();
        assert_eq!(fs::read(&path).unwrap(), b"second");
        let leftovers: Vec<_> = fs::read_dir(&dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| e.file_name().to_string_lossy().contains(".tmp"))
            .collect();
        assert!(leftovers.is_empty(), "temp file not cleaned up by rename");
    }

    // ── Global-vault flow tests (serialized via TEST_LOCK) ────────────────

    /// Stand up a sealed + unlocked vault the way the ceremony does, minus the
    /// device-only reveal/verify (begin → seal). The headless stand-in for the
    /// retired `create_vault` (D-038).
    pub(crate) fn seal_test_vault(passphrase: Vec<u8>, params: VaultKdfParams) {
        begin_create().unwrap();
        seal_and_persist(passphrase, Vec::new(), params).unwrap();
    }

    #[test]
    fn create_lock_unlock_round_trip() {
        let (_g, _dir) = enter();
        let pw = b"correct horse battery".to_vec();

        assert!(!vault_exists());
        seal_test_vault(pw.clone(), cheap_params());
        assert!(vault_exists());
        assert!(current_status().unlocked);

        lock_vault();
        assert!(!current_status().unlocked);
        assert!(current_status().exists); // blob persists across lock

        unlock_with_passphrase(pw).unwrap();
        assert!(current_status().unlocked);
        lock_vault();
    }

    #[test]
    fn seal_refuses_to_overwrite_existing_vault() {
        let (_g, _dir) = enter();
        seal_test_vault(b"pw-one".to_vec(), cheap_params());
        // Seal's own guard (defense-in-depth beside begin_create's): handed a
        // ceremony past begin's gate, it must STILL refuse over an existing vault.
        *CREATE_CEREMONY
            .lock()
            .unwrap_or_else(PoisonError::into_inner) = Some(MnemonicCeremony::generate().unwrap());
        let again = seal_and_persist(b"pw-two".to_vec(), Vec::new(), cheap_params());
        assert!(again.is_err(), "seal must refuse over an existing vault");
        abandon_create();
        lock_vault();
    }

    #[test]
    fn wrong_passphrase_advances_lockout_and_survives_restart() {
        let (_g, dir) = enter();
        seal_test_vault(b"the-real-one".to_vec(), cheap_params());
        lock_vault();

        // Three wrong attempts.
        for expected in 1..=3u32 {
            assert!(unlock_with_passphrase(b"wrong".to_vec()).is_err());
            assert_eq!(current_status().failed_attempts, expected);
        }

        // Simulate a process restart: drop the in-memory state, re-init from the
        // same on-disk directory. The counter must NOT reset (wallet-security 11).
        *VAULT.lock().unwrap_or_else(PoisonError::into_inner) = None;
        *VAULT_DIR.lock().unwrap_or_else(PoisonError::into_inner) = None;
        init_vault(dir.to_string_lossy().to_string()).unwrap();
        assert_eq!(
            current_status().failed_attempts,
            3,
            "lockout counter did not survive restart"
        );

        // The correct passphrase still works and clears the counter.
        unlock_with_passphrase(b"the-real-one".to_vec()).unwrap();
        assert_eq!(current_status().failed_attempts, 0);
        lock_vault();
    }

    #[test]
    fn locked_out_unlock_is_refused_before_the_kdf() {
        let (_g, _dir) = enter();
        seal_test_vault(b"pw".to_vec(), cheap_params());
        lock_vault();

        // Force an active lockout window directly, then time the refusal: it
        // must return without paying the KDF (the whole point of pre-checking).
        write_lockout(Lockout {
            failed_attempts: 9,
            locked_until_unix: now_unix() + 600,
        })
        .unwrap();
        let started = std::time::Instant::now();
        let res = unlock_with_passphrase(b"pw".to_vec());
        assert!(res.is_err());
        assert!(
            started.elapsed().as_millis() < 100,
            "refusal ran the KDF instead of short-circuiting"
        );
        // Clear it so we leave clean state.
        write_lockout(Lockout::default()).unwrap();
        lock_vault();
    }

    /// Regression pin for the live on-device find (2026-06-13): concurrent
    /// wrong-passphrase attempts must EACH advance the counter — the lost
    /// update came from the read-modify-write spanning the KDF. With the
    /// UNLOCK_GATE they serialize; the count is exact, never racy.
    #[test]
    fn concurrent_failed_unlocks_are_all_counted() {
        let (_g, _dir) = enter();
        seal_test_vault(b"the-real-one".to_vec(), cheap_params());
        lock_vault();

        std::thread::scope(|s| {
            for _ in 0..2 {
                s.spawn(|| {
                    assert!(unlock_with_passphrase(b"wrong".to_vec()).is_err());
                });
            }
        });

        assert_eq!(
            current_status().failed_attempts,
            2,
            "a concurrent failure was lost (attempt counter raced)"
        );
        write_lockout(Lockout::default()).unwrap();
    }

    #[test]
    fn init_vault_is_idempotent_but_refuses_to_re_home() {
        let (_g, dir) = enter();
        let same = dir.to_string_lossy().to_string();
        // Same path again (hot restart): fine.
        init_vault(same.clone()).unwrap();
        // A different path: refused, and the original home is kept.
        let other = fresh_dir().to_string_lossy().to_string();
        assert!(init_vault(other).is_err());
        assert_eq!(vault_dir().unwrap(), dir);
        // Same path still accepted after the refusal.
        init_vault(same).unwrap();
    }

    #[test]
    fn export_seed_requires_unlocked_and_matches_the_sealed_seed() {
        let (_g, _dir) = enter();
        seal_test_vault(b"pw".to_vec(), cheap_params());
        // Unlocked: export yields 64 bytes (the live seed the Keystore wraps).
        let exported = export_seed_for_keystore().unwrap();
        assert_eq!(exported.len(), 64);

        lock_vault();
        // Locked: refuse to export.
        assert!(export_seed_for_keystore().is_err());

        // Path-A unlock with those same bytes restores the vault.
        load_vault_from_seed_bytes(Box::new(*exported)).unwrap();
        assert!(current_status().unlocked);
        lock_vault();
    }

    // ── P1.4 create-ceremony + restore (D-037 / D-038) ────────────────────

    #[test]
    fn create_ceremony_begin_reveal_seal_round_trip() {
        let (_g, _dir) = enter();
        assert!(!vault_exists());
        begin_create().unwrap();
        // The reveal lane yields exactly 12 space-separated words.
        let revealed = reveal_ceremony_words().unwrap();
        let phrase = std::str::from_utf8(&revealed).unwrap();
        assert_eq!(phrase.split(' ').count(), 12, "reveal must expose 12 words");
        // Sealing consumes the ceremony, persists, leaves the vault unlocked.
        seal_and_persist(b"correct horse".to_vec(), Vec::new(), cheap_params()).unwrap();
        assert!(vault_exists());
        assert!(current_status().unlocked);
        // Consumed: the reveal lane now refuses.
        assert!(reveal_ceremony_words().is_err());
        lock_vault();
    }

    #[test]
    fn begin_refuses_double_ceremony_and_existing_vault() {
        let (_g, _dir) = enter();
        begin_create().unwrap();
        assert!(begin_create().is_err(), "a second ceremony must refuse");
        abandon_create();
        seal_test_vault(b"pw".to_vec(), cheap_params());
        assert!(
            begin_create().is_err(),
            "begin must refuse when a vault exists"
        );
        lock_vault();
    }

    #[test]
    fn abandon_and_lifecycle_lock_drop_the_ceremony() {
        let (_g, _dir) = enter();
        begin_create().unwrap();
        assert!(reveal_ceremony_words().is_ok());
        abandon_create();
        assert!(
            reveal_ceremony_words().is_err(),
            "abandon must drop the held ceremony"
        );
        // lock_vault is the §0.11 lifecycle hook: it also drops an in-progress
        // ceremony, so a backgrounded reveal leaves no phrase resident.
        begin_create().unwrap();
        lock_vault();
        assert!(
            reveal_ceremony_words().is_err(),
            "lifecycle lock must drop the held ceremony"
        );
    }

    #[test]
    fn seal_refuses_non_ascii_extra_word_without_consuming_the_ceremony() {
        let (_g, _dir) = enter();
        begin_create().unwrap();
        let non_ascii = "café".as_bytes().to_vec(); // é is non-ASCII
        assert!(
            seal_and_persist(b"pw".to_vec(), non_ascii, cheap_params()).is_err(),
            "create path must refuse a non-ASCII extra word (D-031.5)"
        );
        // The rejected attempt did NOT consume the ceremony — a retry can seal.
        assert!(reveal_ceremony_words().is_ok());
        seal_and_persist(b"pw".to_vec(), b"backup-word".to_vec(), cheap_params()).unwrap();
        assert!(current_status().unlocked);
        lock_vault();
    }

    #[test]
    fn restore_preview_derives_an_address_without_persisting() {
        let (_g, _dir) = enter();
        // Upstream's 24-word vector (keychain.rs / mnemonic.rs).
        let phrase = b"fringe ceiling crater inject pilot travel gas nurse bulb bullet horn segment snack harbor dice laugh vital cigar push couple plastic into slender worry".to_vec();
        let addr = restore_preview(phrase, Vec::new()).unwrap();
        assert!(
            addr.starts_with("kaspa:"),
            "preview must be a mainnet address"
        );
        assert!(!vault_exists(), "a preview must never create a vault");
    }

    #[test]
    fn restore_preview_extra_word_changes_the_derived_address() {
        let (_g, _dir) = enter();
        let phrase =
            b"abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
                .to_vec();
        let plain = restore_preview(phrase.clone(), Vec::new()).unwrap();
        let salted = restore_preview(phrase, b"TREZOR".to_vec()).unwrap();
        assert_ne!(
            plain, salted,
            "the extra word must derive a visibly different wallet (decoy property)"
        );
    }

    #[test]
    fn restore_and_persist_round_trips_through_passphrase_unlock() {
        let (_g, _dir) = enter();
        let phrase =
            b"abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
                .to_vec();
        restore_and_persist(phrase, Vec::new(), b"pw".to_vec(), cheap_params()).unwrap();
        assert!(vault_exists());
        assert!(current_status().unlocked);
        lock_vault();
        // The restored vault unlocks with the same passphrase.
        unlock_with_passphrase(b"pw".to_vec()).unwrap();
        assert!(current_status().unlocked);
        lock_vault();
    }
}
