// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fold`, `shared_monitor`, `snapshots`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Subscribe to live DAG snapshots from mainnet. The first call connects;
/// later calls share the same connection. Each stream ends only when its
/// Dart listener goes away.
Stream<DagSnapshot> subscribeDagUpdates() =>
    RustLib.instance.api.crateApiDagSubscribeDagUpdates();

/// Live view of the DAG tip as seen over wRPC, streamed on every change.
/// Scores stay `u64` end-to-end (they exceed 2^53 — Dart sees `BigInt`, L3).
class DagSnapshot {
  final bool connected;

  /// Node endpoint picked by the PNN resolver (`None` until first connect).
  final String? endpoint;
  final BigInt? virtualDaaScore;
  final BigInt? sinkBlueScore;

  const DagSnapshot({
    required this.connected,
    this.endpoint,
    this.virtualDaaScore,
    this.sinkBlueScore,
  });

  static Future<DagSnapshot> default_() =>
      RustLib.instance.api.crateApiDagDagSnapshotDefault();

  @override
  int get hashCode =>
      connected.hashCode ^
      endpoint.hashCode ^
      virtualDaaScore.hashCode ^
      sinkBlueScore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DagSnapshot &&
          runtimeType == other.runtimeType &&
          connected == other.connected &&
          endpoint == other.endpoint &&
          virtualDaaScore == other.virtualDaaScore &&
          sinkBlueScore == other.sinkBlueScore;
}
