// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `current_endpoint_url`, `escalation_task`, `fold`, `retention`, `shared_monitor`, `shared_tracker`, `snapshots`, `tracker_handle`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`

/// The session's recorded span markers, oldest first. Pull surface — the
/// harness and the debug screen poll it; nothing streams.
Future<List<SpanMarkerDto>> perfSpans() =>
    RustLib.instance.api.crateApiDagPerfSpans();

/// Background grace-drop (PERFORMANCE_BUDGET battery posture): close the wRPC
/// socket and stop the retry loop. Dart's ChainService calls this ~30 s after
/// the app backgrounds. A no-op before the first connection exists.
Future<void> dagPause() => RustLib.instance.api.crateApiDagDagPause();

/// Foreground resume after a grace-drop: reconnect, preferring the last-good
/// endpoint (fast path), resolver fallback. No-op while already connected.
Future<void> dagResume() => RustLib.instance.api.crateApiDagDagResume();

/// Read the current connection health (see [`DagStatusDto`]). Endpoint + DAA
/// come from the folded snapshot; connected + block-age come straight from the
/// monitor so a silently dead socket (still `connected` in the snapshot) is
/// caught by a growing block-age.
Future<DagStatusDto> dagStatus() => RustLib.instance.api.crateApiDagDagStatus();

/// Force a fresh wRPC connection — the Reconnect button and the watchdog's
/// recovery (P3/D-068). Hard-drops even a socket the client believes is alive,
/// then re-races (the cached endpoint is candidate 0 — the fast path). A no-op
/// before the first connect exists (nothing to bounce).
///
/// `stalled = true` when the CALLER has failure evidence against the current
/// endpoint (the watchdog's 30 s block silence): it becomes a pending strike
/// the race commits only if another healthy node answers (V3 demotion,
/// control-group rule). The manual Reconnect button passes `false` — bouncing
/// a healthy node must never demote it.
Future<void> dagReconnect({required bool stalled}) =>
    RustLib.instance.api.crateApiDagDagReconnect(stalled: stalled);

/// V3 register item 12: the pull heal asks the NODE. A swipe-to-refresh calls
/// this to force a resync — a hard reconnect through the race, which lands in
/// wallet-core's `UtxoProcStart` and a fresh address scan, exactly the
/// detection path a kill/relaunch used to be needed for. Rate-limited; returns
/// `true` when a resync was actually triggered, `false` when the window
/// swallowed it (the caller still re-serves the fold — delivery heal — so a
/// swallowed pull is never a dead gesture).
Future<bool> dagResync() => RustLib.instance.api.crateApiDagDagResync();

/// Subscribe to live DAG snapshots from mainnet. The first call connects;
/// later calls share the same connection. Each stream ends only when its
/// Dart listener goes away.
Stream<DagSnapshot> subscribeDagUpdates() =>
    RustLib.instance.api.crateApiDagSubscribeDagUpdates();

/// Live view of the DAG tip as seen over wRPC, streamed on every change.
/// Scores stay `u64` end-to-end (they exceed 2^53 — Dart sees `BigInt`, L3).
class DagSnapshot {
  final bool connected;

  /// Node endpoint picked by the PNN resolver (`None` until first connect).
  final String? endpoint;
  final BigInt? virtualDaaScore;
  final BigInt? sinkBlueScore;

  const DagSnapshot({
    required this.connected,
    this.endpoint,
    this.virtualDaaScore,
    this.sinkBlueScore,
  });

  static Future<DagSnapshot> default_() =>
      RustLib.instance.api.crateApiDagDagSnapshotDefault();

  @override
  int get hashCode =>
      connected.hashCode ^
      endpoint.hashCode ^
      virtualDaaScore.hashCode ^
      sinkBlueScore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DagSnapshot &&
          runtimeType == other.runtimeType &&
          connected == other.connected &&
          endpoint == other.endpoint &&
          virtualDaaScore == other.virtualDaaScore &&
          sinkBlueScore == other.sinkBlueScore;
}

/// Honest-liveness snapshot for the connection-health sheet AND the foreground
/// watchdog (P3/D-068). A PULL surface (not the stream): the sheet paints it on
/// open and the watchdog polls it. `last_block_age_secs` is the load-bearing
/// field — a healthy mainnet keeps it near zero (~10 blocks/s); a large value
/// while foreground means a silently dead socket (the midnight DAA stall), the
/// watchdog's trigger to [`dag_reconnect`]. `None` before the first connect.
class DagStatusDto {
  final bool connected;
  final String? endpoint;
  final BigInt? lastBlockAgeSecs;
  final BigInt? virtualDaaScore;

  const DagStatusDto({
    required this.connected,
    this.endpoint,
    this.lastBlockAgeSecs,
    this.virtualDaaScore,
  });

  static Future<DagStatusDto> default_() =>
      RustLib.instance.api.crateApiDagDagStatusDtoDefault();

  @override
  int get hashCode =>
      connected.hashCode ^
      endpoint.hashCode ^
      lastBlockAgeSecs.hashCode ^
      virtualDaaScore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DagStatusDto &&
          runtimeType == other.runtimeType &&
          connected == other.connected &&
          endpoint == other.endpoint &&
          lastBlockAgeSecs == other.lastBlockAgeSecs &&
          virtualDaaScore == other.virtualDaaScore;
}

/// One span marker crossing the FFI (V1 observability — findings-register
/// item 6, founder-ratified): PUBLIC data only (marker name, optional txid,
/// timestamp). This is the L40-proof lane: Dart prints/collects these on any
/// build flavor; the perf harness reads the same query.
class SpanMarkerDto {
  final String marker;

  /// A txid or small public value (e.g. gap minutes); `None` for bare marks.
  final String? detail;
  final BigInt unixMs;

  const SpanMarkerDto({
    required this.marker,
    this.detail,
    required this.unixMs,
  });

  @override
  int get hashCode => marker.hashCode ^ detail.hashCode ^ unixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpanMarkerDto &&
          runtimeType == other.runtimeType &&
          marker == other.marker &&
          detail == other.detail &&
          unixMs == other.unixMs;
}
