// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `prefs_dir`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`

/// Read the explorer choice (file-backed; defaults to the first shipped one).
Future<ExplorerConfigDto> prefsExplorerConfig() =>
    RustLib.instance.api.crateApiPrefsPrefsExplorerConfig();

/// Persist the explorer choice. Both templates are validated in Rust — the
/// render layer never parses or builds a URL — and a rejected save leaves the
/// previous choice untouched, so a typo cannot cost a user their explorer.
Future<void> prefsSetExplorerConfig({
  required String txTemplate,
  required String addressTemplate,
}) => RustLib.instance.api.crateApiPrefsPrefsSetExplorerConfig(
  txTemplate: txTemplate,
  addressTemplate: addressTemplate,
);

/// The exact URL this wallet would open for `txid`.
///
/// Exposed because disclosure is only real if it is specific: the settings row
/// shows the resolved link rather than describing one, and the exit that
/// eventually opens it (UX-5) calls the same function.
Future<String> prefsExplorerTxUrl({required String txid}) =>
    RustLib.instance.api.crateApiPrefsPrefsExplorerTxUrl(txid: txid);

/// The exact URL this wallet would open for `address`.
Future<String> prefsExplorerAddressUrl({required String address}) =>
    RustLib.instance.api.crateApiPrefsPrefsExplorerAddressUrl(address: address);

/// Read the rate posture (file-backed; ON by default — founder call,
/// 2026-08-27, recorded with its INV-8 concession in the ledger).
Future<RateConfigDto> prefsRateConfig() =>
    RustLib.instance.api.crateApiPrefsPrefsRateConfig();

/// Persist the rate posture. An empty endpoint means "back to the shipped
/// default" rather than an error — the field's clear button has to lead
/// somewhere (`transport_set_fill_config`'s contract).
Future<void> prefsSetRateConfig({
  required bool enabled,
  required String endpoint,
}) => RustLib.instance.api.crateApiPrefsPrefsSetRateConfig(
  enabled: enabled,
  endpoint: endpoint,
);

/// Fetch one price, or `None` because the rate is off — a refusal the layer
/// below makes, before any socket exists.
///
/// An error means *no usable price*, and the caller must render `—` rather
/// than a stale-but-confident number of its own invention. A caller holding an
/// older quote may keep showing it **with its age** (BG-8's dimmed-cached-truth
/// rule, applied to the one datum consensus cannot check).
Future<RateQuoteDto?> prefsRateQuote() =>
    RustLib.instance.api.crateApiPrefsPrefsRateQuote();

/// The explorer choice, plus what the user could return to.
class ExplorerConfigDto {
  final String txTemplate;
  final String addressTemplate;

  /// The audited defaults, in ship order. The row renders these as one-tap
  /// starting points beside the editable field.
  final List<ExplorerDefaultDto> defaults;

  const ExplorerConfigDto({
    required this.txTemplate,
    required this.addressTemplate,
    required this.defaults,
  });

  @override
  int get hashCode =>
      txTemplate.hashCode ^ addressTemplate.hashCode ^ defaults.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExplorerConfigDto &&
          runtimeType == other.runtimeType &&
          txTemplate == other.txTemplate &&
          addressTemplate == other.addressTemplate &&
          defaults == other.defaults;
}

/// One shipped explorer, offered as a starting point. Both are replaceable —
/// a list only we can edit is not a sovereignty decision (D-207).
class ExplorerDefaultDto {
  final String name;
  final String txTemplate;
  final String addressTemplate;

  const ExplorerDefaultDto({
    required this.name,
    required this.txTemplate,
    required this.addressTemplate,
  });

  @override
  int get hashCode =>
      name.hashCode ^ txTemplate.hashCode ^ addressTemplate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExplorerDefaultDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          txTemplate == other.txTemplate &&
          addressTemplate == other.addressTemplate;
}

/// The rate posture, plus the endpoint a user can return to.
class RateConfigDto {
  final bool enabled;
  final String endpoint;
  final String defaultEndpoint;

  const RateConfigDto({
    required this.enabled,
    required this.endpoint,
    required this.defaultEndpoint,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^ endpoint.hashCode ^ defaultEndpoint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RateConfigDto &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          endpoint == other.endpoint &&
          defaultEndpoint == other.defaultEndpoint;
}

/// One price, fetched now — or `None` because the user switched the rate off.
///
/// `usd_per_kas` is a **display** number and nothing else: it never prices a
/// fee, sizes a spend, or reaches a signing surface (INV-8's carve-out, BG-5).
/// `fetched_at_unix_ms` is stamped here so the age the glass shows is the age
/// of the fetch, not of the Dart frame that rendered it.
class RateQuoteDto {
  final double usdPerKas;
  final BigInt fetchedAtUnixMs;

  /// The endpoint this price came from — the source the disclosure names.
  final String source;

  const RateQuoteDto({
    required this.usdPerKas,
    required this.fetchedAtUnixMs,
    required this.source,
  });

  @override
  int get hashCode =>
      usdPerKas.hashCode ^ fetchedAtUnixMs.hashCode ^ source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RateQuoteDto &&
          runtimeType == other.runtimeType &&
          usdPerKas == other.usdPerKas &&
          fetchedAtUnixMs == other.fetchedAtUnixMs &&
          source == other.source;
}
