// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fully_broadcast`, `kas_display`, `validate_mainnet_address`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// The smallest amount currently sendable from this wallet's coins (the KIP-9
/// floor for the live UTXO shape, computed by probing the pinned Generator —
/// D-054), or `None` when the wallet cannot send at all / isn't ready. Public
/// data only; signerless; no cursor movement (peeks the current change address).
Future<BigInt?> sendMinimum() => RustLib.instance.api.crateApiSendSendMinimum();

/// Phase 1: validate, build the tx chain over the live UTXO context, and stash
/// the unsigned transactions. Returns the Rust-decoded summary for the confirm.
/// Errors honestly: malformed/wrong-network address, locked/unready wallet, or
/// a funds shortfall classified as "not yet spendable" vs "insufficient" using
/// the live balance.
Future<SendSummaryDto> sendPrepare({
  required String destination,
  required BigInt amountSompi,
}) => RustLib.instance.api.crateApiSendSendPrepare(
  destination: destination,
  amountSompi: amountSompi,
);

/// Phase 2: sign + broadcast the stashed plan identified by `nonce`. Refuses a
/// stale/mismatched nonce or an empty stash (the user re-confirms). Advances the
/// change cursor only on a fully-broadcast send.
Future<SendOutcomeDto> sendCommit({required BigInt nonce}) =>
    RustLib.instance.api.crateApiSendSendCommit(nonce: nonce);

/// Drop any stashed send (confirm dismissed / back-gesture). Idempotent.
Future<void> sendAbandon() => RustLib.instance.api.crateApiSendSendAbandon();

/// The outcome of broadcasting. `partial` (B6): some legs are already on-chain
/// (their UTXOs really spent) — surfaced, never hidden; the next sync reconciles.
class SendOutcomeDto {
  final String? finalTxid;
  final int submitted;
  final int total;
  final bool partial;
  final String? error;

  const SendOutcomeDto({
    this.finalTxid,
    required this.submitted,
    required this.total,
    required this.partial,
    this.error,
  });

  @override
  int get hashCode =>
      finalTxid.hashCode ^
      submitted.hashCode ^
      total.hashCode ^
      partial.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendOutcomeDto &&
          runtimeType == other.runtimeType &&
          finalTxid == other.finalTxid &&
          submitted == other.submitted &&
          total == other.total &&
          partial == other.partial &&
          error == other.error;
}

/// The Rust-decoded summary the confirm screen renders (B7) — NOT the form echo.
/// `nonce` guards [`send_commit`] against a stale plan; `*_sompi`/`mass` cross as
/// Dart `BigInt` (L3).
class SendSummaryDto {
  /// Opaque token tying this summary to its stashed transactions.
  final BigInt nonce;

  /// The mainnet address Rust validated and built into the payment output.
  final String destination;
  final BigInt amountSompi;

  /// The Generator's exact aggregate fee — never "≈ free" (KIP-9 storage mass).
  final BigInt feeSompi;

  /// `amount + fee` (what leaves the wallet, excluding returned change).
  final BigInt totalSompi;
  final BigInt mass;

  /// 1 normally; >1 when the send chained past one tx's 100k-gram mass.
  final int txCount;
  final int utxoCount;

  const SendSummaryDto({
    required this.nonce,
    required this.destination,
    required this.amountSompi,
    required this.feeSompi,
    required this.totalSompi,
    required this.mass,
    required this.txCount,
    required this.utxoCount,
  });

  @override
  int get hashCode =>
      nonce.hashCode ^
      destination.hashCode ^
      amountSompi.hashCode ^
      feeSompi.hashCode ^
      totalSompi.hashCode ^
      mass.hashCode ^
      txCount.hashCode ^
      utxoCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendSummaryDto &&
          runtimeType == other.runtimeType &&
          nonce == other.nonce &&
          destination == other.destination &&
          amountSompi == other.amountSompi &&
          feeSompi == other.feeSompi &&
          totalSompi == other.totalSompi &&
          mass == other.mass &&
          txCount == other.txCount &&
          utxoCount == other.utxoCount;
}
