// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `commit_and_advance`, `fully_broadcast`, `kas_exact`, `map_drain_error`, `next_nonce`, `payment_change_address`, `project_signable`, `shortfall_message`, `spend_exclusions`, `storage_mass_message`, `take_stashed`, `validate_mainnet_address`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// The smallest amount currently sendable from this wallet's coins (the KIP-9
/// floor for the live UTXO shape, computed by probing the pinned Generator —
/// D-054), or `None` when the wallet cannot send at all / isn't ready. Public
/// data only; signerless; probes with the address the send will really use, so
/// the advertised floor is the floor of the transaction that gets built.
Future<BigInt?> sendMinimum() => RustLib.instance.api.crateApiSendSendMinimum();

/// Phase 1: validate, build the tx chain over the live UTXO context, and stash
/// the unsigned transactions. Returns the Rust-decoded summary for the confirm.
/// Errors honestly: malformed/wrong-network address, locked/unready wallet, or
/// a funds shortfall classified as "not yet spendable" vs "insufficient" using
/// the live balance.
Future<SignableSummaryDto> sendPrepare({
  required String destination,
  required BigInt amountSompi,
}) => RustLib.instance.api.crateApiSendSendPrepare(
  destination: destination,
  amountSompi: amountSompi,
);

/// Phase 1 of the wallet's EXIT: build the sweep — every spendable coin, from
/// every watched address, to `destination` in one transaction — stash it, and
/// return the B7 summary. The swept amount is the BUILT transaction's single
/// output (the fee already deducted by the Generator), so the confirm renders
/// exactly what the destination receives and `amount + fee == balance` to the
/// sompi. Commit rides the ordinary [`send_commit`] path with the same nonce
/// guard, acceptance watch, and abandon affordance.
Future<SignableSummaryDto> sweepPrepare({required String destination}) =>
    RustLib.instance.api.crateApiSendSweepPrepare(destination: destination);

/// Phase 1 of consolidation: merge the wallet's spendable coins into ONE coin
/// at receive/0, leaving live conversations' bound addresses untouched
/// (`transport::drain_exclusions` — fails closed if the transport store is
/// unavailable). The preview carries the honest savings pair when it can be
/// priced; a preview probe failing never fails the consolidation itself (an
/// optional extra that can delete the action it decorates is worse than no
/// extra — the send-hint scar, SOURCE_OF_TRUTH §19).
Future<SignableSummaryDto> consolidatePrepare() =>
    RustLib.instance.api.crateApiSendConsolidatePrepare();

/// Phase 2: sign + broadcast the stashed plan identified by `nonce`. Refuses a
/// stale/mismatched nonce or an empty stash (the user re-confirms). Advances the
/// change cursor only on a fully-broadcast send.
Future<SendOutcomeDto> sendCommit({required BigInt nonce}) =>
    RustLib.instance.api.crateApiSendSendCommit(nonce: nonce);

/// Drop any stashed send (confirm dismissed / back-gesture). Idempotent.
Future<void> sendAbandon() => RustLib.instance.api.crateApiSendSendAbandon();

/// Reserved fee-strategy discriminant (V5). One variant today — every flow
/// pays `Fees::SenderPays(priority)` at the pinned Generator
/// (`chain::send::prepare_send_inner`) with `priority_fee_sompi = 0`. The
/// seam for a later estimate/fee-choice (★ Send-UX pass, D-008/RBF-deferred);
/// fee ESTIMATION is deliberately not built here.
enum FeeStrategyKind { senderPays }

/// The outcome of broadcasting. `partial` (B6): some legs are already on-chain
/// (their UTXOs really spent) — surfaced, never hidden; the next sync reconciles.
class SendOutcomeDto {
  final String? finalTxid;
  final int submitted;
  final int total;
  final bool partial;
  final String? error;

  const SendOutcomeDto({
    this.finalTxid,
    required this.submitted,
    required this.total,
    required this.partial,
    this.error,
  });

  @override
  int get hashCode =>
      finalTxid.hashCode ^
      submitted.hashCode ^
      total.hashCode ^
      partial.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendOutcomeDto &&
          runtimeType == other.runtimeType &&
          finalTxid == other.finalTxid &&
          submitted == other.submitted &&
          total == other.total &&
          partial == other.partial &&
          error == other.error;
}

/// Which send-like flow a signable summary describes — set by RUST from its
/// own flow knowledge, never caller-supplied (V5: the Dart `selfSend` bool
/// was the last un-Rust-vouched fact on the signing surface; the mode now
/// rides the same B7-decoded DTO as the numbers). Field-less by the FRB DTO
/// law (dag.rs note): per-kind facts ride [`SignableSummaryDto`]'s `Option`
/// fields — payment mode never sees frame fields.
enum SignableKind {
  /// Plain payment: value to a counterparty, no payload.
  payment,

  /// Outbound handshake: the 0.2 KAS bond to the counterparty + sealed
  /// payload (§0.6 — refunded in their acceptance).
  bond,

  /// Accept: the bond REFUNDED to the sender + sealed payload. Value moves
  /// to the counterparty — deliberately NOT a self-send (D-069 keeps
  /// bonds unchanged).
  bondRefund,

  /// Comm/frame self-send (D-069): destination is our OWN bound address,
  /// value returns as change — the honest cost is the fee alone. The
  /// sheet leads with the fee and never states the value as spend.
  selfSendFrame,

  /// The P4 challenge/stake seam: value at RISK into a covenant + game
  /// frame. No producer yet — reserved so P4 adds a producer, never a
  /// sixth confirm sheet (the V5 variant-coverage bar; render-pinned by
  /// the Dart B7 suite).
  stake,

  /// Dev/broadcast lane: plaintext payload to an arbitrary address.
  bcast,

  /// Sweep — send max, the wallet's EXIT: every spendable coin, from every
  /// watched address, to an external destination in ONE transaction whose
  /// output + fee equal the balance to the sompi. The amount is SOLVED by
  /// the Rust builder (it depends on the fee of the transaction spending
  /// it), never typed or computed in Dart.
  sweep,

  /// Consolidate — the wallet's spendable coins merged into ONE coin at
  /// receive/0, so future sends pay the one-input floor. Coins at live
  /// conversations' bound addresses are excluded (`drain_exclusions`) and
  /// the chain layer refuses on the BUILT transaction if one is drawn.
  consolidate,
}

/// THE canonical Rust-decoded summary every signable flow renders (B7 — NOT
/// the form echo; V5 consolidation, one signing surface for P4 to extend).
/// `nonce` guards the commit against a stale plan; `*_sompi`/`mass` cross as
/// Dart `BigInt` (L3); `payload_*` are decoded from the BUILT final tx and
/// are `None` exactly when the flow carries no payload.
class SignableSummaryDto {
  /// Opaque token tying this summary to its stashed transactions.
  final BigInt nonce;

  /// The flow mode — Rust's knowledge, the sheet's render switch.
  final SignableKind kind;

  /// The mainnet address Rust validated and built into the payment output.
  final String destination;
  final BigInt amountSompi;

  /// The Generator's exact aggregate fee — never "≈ free". The basis is the
  /// wallet's minimum-relay proxy: ≈ compute mass, with the payload
  /// component hardened for normalized transient bytes (so payload-bearing
  /// flows are priced in here); storage mass is EXCLUDED from the floor,
  /// which is why `mass` below never reconciles with this number.
  final BigInt feeSompi;

  /// `amount + fee` (what leaves the wallet, excluding returned change).
  final BigInt totalSompi;
  final BigInt mass;

  /// 1 normally; >1 when the send chained past one tx's 100k-gram mass.
  /// **A transaction count is not a coin count** — see `resulting_coins`.
  final int txCount;
  final int utxoCount;

  /// How many coins the send LEAVES at its destination (0 where the question
  /// does not apply — every kind but a merge). Read straight off the built
  /// chain by the layer that knows which drain arm ran, because the two arms
  /// both chain and leave opposite results (ux audit, this sitting).
  final int resultingCoins;

  /// Payload bytes on the built final tx (read back, not echoed); `None`
  /// on a payload-less flow — payment mode never sees frame fields.
  final int? payloadLen;

  /// Wire kind decoded from the built payload (same parser the receive
  /// scan uses); `None` on a payload-less flow.
  final String? payloadKind;

  /// Reserved (V5): the strategy the stashed plan was built with.
  final FeeStrategyKind feeStrategy;

  /// Reserved (V5): the priority component — 0 today, everywhere.
  final BigInt priorityFeeSompi;

  /// Consolidate only (`None` on every other kind): the representative
  /// amount the savings comparison below was priced at — half the
  /// consolidated value, an ordinary mid-shape send.
  final BigInt? typicalAmountSompi;

  /// Consolidate only: inputs that send draws from TODAY's coins.
  final int? typicalNowUtxos;

  /// Consolidate only: its fee from today's coins.
  final BigInt? typicalNowFeeSompi;

  /// Consolidate only: the same send's fee from the single consolidated
  /// coin. All four are the pinned Generator's own numbers over real
  /// shapes (probed in `chain::send::consolidation_savings`), never
  /// arithmetic done here or in Dart.
  final BigInt? typicalAfterFeeSompi;

  const SignableSummaryDto({
    required this.nonce,
    required this.kind,
    required this.destination,
    required this.amountSompi,
    required this.feeSompi,
    required this.totalSompi,
    required this.mass,
    required this.txCount,
    required this.utxoCount,
    required this.resultingCoins,
    this.payloadLen,
    this.payloadKind,
    required this.feeStrategy,
    required this.priorityFeeSompi,
    this.typicalAmountSompi,
    this.typicalNowUtxos,
    this.typicalNowFeeSompi,
    this.typicalAfterFeeSompi,
  });

  @override
  int get hashCode =>
      nonce.hashCode ^
      kind.hashCode ^
      destination.hashCode ^
      amountSompi.hashCode ^
      feeSompi.hashCode ^
      totalSompi.hashCode ^
      mass.hashCode ^
      txCount.hashCode ^
      utxoCount.hashCode ^
      resultingCoins.hashCode ^
      payloadLen.hashCode ^
      payloadKind.hashCode ^
      feeStrategy.hashCode ^
      priorityFeeSompi.hashCode ^
      typicalAmountSompi.hashCode ^
      typicalNowUtxos.hashCode ^
      typicalNowFeeSompi.hashCode ^
      typicalAfterFeeSompi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignableSummaryDto &&
          runtimeType == other.runtimeType &&
          nonce == other.nonce &&
          kind == other.kind &&
          destination == other.destination &&
          amountSompi == other.amountSompi &&
          feeSompi == other.feeSompi &&
          totalSompi == other.totalSompi &&
          mass == other.mass &&
          txCount == other.txCount &&
          utxoCount == other.utxoCount &&
          resultingCoins == other.resultingCoins &&
          payloadLen == other.payloadLen &&
          payloadKind == other.payloadKind &&
          feeStrategy == other.feeStrategy &&
          priorityFeeSompi == other.priorityFeeSompi &&
          typicalAmountSompi == other.typicalAmountSompi &&
          typicalNowUtxos == other.typicalNowUtxos &&
          typicalNowFeeSompi == other.typicalNowFeeSompi &&
          typicalAfterFeeSompi == other.typicalAfterFeeSompi;
}
