// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'send.dart';

// These functions are ignored because they are not marked as `pub`: `adopt_alias_from_sender`, `alias_already_parked`, `any`, `apply_intent`, `build`, `clamp_display`, `comm_is_dismissed`, `comm_sendable`, `decrypt_drop`, `dropped`, `fill_walks`, `format_kas`, `frame_dto`, `friendly_prepare_error`, `handle_inbound_comm`, `handle_inbound_handshake`, `handle_inbound`, `handshake_slots`, `hold`, `hub`, `invite_expired`, `keys`, `kind_of_intent`, `may_unhide`, `new`, `notice`, `now_unix_ms`, `open_with_fallback`, `outcome`, `park_alias`, `ping_notice_inputs`, `ping`, `prepare_comm_plaintext`, `prepare_transport_send`, `resolve_gap_age`, `resolve_handshake_sender`, `resume_from`, `row_source_label`, `row_source`, `run_fill`, `split_frame`, `stash_intent`, `tail_start`, `take_intent`, `take_parked_alias`, `thread_pings`, `thread_row`, `to_core_branch`, `to_dto`, `to_key_branch`, `tx_status_dto`, `unhide_on_inbound`, `warn_store`, `watch_acceptance`, `widen_key_window`, `x_only_of`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DropReason`, `EventOrigin`, `FoldOutcome`, `HeldFloor`, `KeyWindow`, `TransportHub`, `TransportIntent`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// The gap-age computed at this open (`None` until resolved / first run).
/// Pull surface for V2b's notice; also logged + span-marked when resolved.
Future<GapAgeDto?> transportGapAge() =>
    RustLib.instance.api.crateApiTransportTransportGapAge();

/// Current fill config (file-backed; defaults OFF + the hosted default).
Future<FillConfigDto> transportFillConfig() =>
    RustLib.instance.api.crateApiTransportTransportFillConfig();

/// Persist the fill posture. The endpoint is validated (http/https) here —
/// a rejected save leaves the previous config untouched.
Future<void> transportSetFillConfig({
  required bool enabled,
  required String endpoint,
}) => RustLib.instance.api.crateApiTransportTransportSetFillConfig(
  enabled: enabled,
  endpoint: endpoint,
);

/// The last fill run's report (`None` = no run this process).
Future<FillReportDto?> transportFillStatus() =>
    RustLib.instance.api.crateApiTransportTransportFillStatus();

/// Run the fill immediately (the settings sheet's "check now"; the open-time
/// auto-run uses the same path). Returns the report it also stores.
Future<FillReportDto> transportFillNow() =>
    RustLib.instance.api.crateApiTransportTransportFillNow();

/// Start (or restart after a re-unlock) the transport hub: load the stores,
/// take a vault-scoped decryptor, derive the PUBLIC watched window, and
/// attach the inbound task to the live `ciph_msg:` scan. Idempotent while
/// the vault stays unlocked; called by Dart alongside the wallet start.
Future<void> transportStart() =>
    RustLib.instance.api.crateApiTransportTransportStart();

/// Phase 1 (dev/broadcast lane): compose `ciph_msg:1:bcast:<channel>:<text>`,
/// build the tx chain over the live UTXO context with the payload on the final
/// tx, and stash it unsigned. Returns the Rust-decoded summary (incl. the
/// payload the BUILT tx carries) for the confirm step.
Future<SignableSummaryDto> transportPrepareBcast({
  required String destination,
  required BigInt amountSompi,
  required String channel,
  required String message,
}) => RustLib.instance.api.crateApiTransportTransportPrepareBcast(
  destination: destination,
  amountSompi: amountSompi,
  channel: channel,
  message: message,
);

/// Phase 1 (initiate a conversation): fresh alias + the live-shape handshake
/// JSON, sealed to the recipient's address key; 0.2 KAS bond (§0.6 — THE one
/// provenance-cited constant, refunded in their acceptance). The plaintext is
/// re-sealed to self HERE so the stash holds ciphertext only (§0.4).
Future<SignableSummaryDto> transportPrepareHandshake({
  required String destination,
}) => RustLib.instance.api.crateApiTransportTransportPrepareHandshake(
  destination: destination,
);

/// Phase 1 (accept an inbound handshake): resolve the SENDER via the node's
/// own return-address lookup (consensus data, never payload content — §0.3:
/// this flow commits value), build the acceptance response, refund the 0.2
/// KAS bond (§0.6).
Future<SignableSummaryDto> transportPrepareAccept({
  required String conversationId,
}) => RustLib.instance.api.crateApiTransportTransportPrepareAccept(
  conversationId: conversationId,
);

/// Phase 1 (a message in an active conversation): seal to the contact's
/// address key, tag the wire with OUR alias (the live convention), and
/// **self-send the value** — the tx destination is our OWN bound address, so
/// the message value returns to us as change and the only real cost is the
/// network fee (§0.6 amended by D-069, founder-approved at the P2.3b sitting).
/// This matches the live population: Kasia comms are self-sends (Gate K §K6);
/// the recipient discovers the message by scanning for our alias in the
/// payload, never by receiving value (their comm intake ignores outputs). The
/// earlier value-to-recipient reading cost ~0.1 KAS/message on the anti-dust
/// floor — proven unusable at the sitting.
Future<SignableSummaryDto> transportPrepareComm({
  required String conversationId,
  required String text,
}) => RustLib.instance.api.crateApiTransportTransportPrepareComm(
  conversationId: conversationId,
  text: text,
);

/// Phase 1 — compose a `kv:1:challenge` (Attack & Defend) as a self-send comm.
/// `stake` is a DISPLAY value in KAS (`None` ⇒ a friendly, no-stake duel); it
/// binds NO value here — frames are hints, the real wager binds at the P3
/// covenant. The readable invite line is GENERATED in `core::frames` from the
/// fields (never free-typed), so it can't misrepresent the card. Rides the
/// shared comm prepare above — no new send-path economics.
Future<SignableSummaryDto> transportPrepareChallenge({
  required String conversationId,
  String? stake,
}) => RustLib.instance.api.crateApiTransportTransportPrepareChallenge(
  conversationId: conversationId,
  stake: stake,
);

/// Phase 1 — compose a social `kv:1:accept` for the challenge `ref_id`. This is
/// NOT a wager and NEVER auto-spends: it is a self-send comm the user confirms
/// through the normal hold-to-sign ceremony (§0.5 law a). NB: deliberately
/// distinct from [`transport_prepare_accept`], the handshake-bond acceptance.
Future<SignableSummaryDto> transportPrepareChallengeAccept({
  required String conversationId,
  required String refId,
}) => RustLib.instance.api.crateApiTransportTransportPrepareChallengeAccept(
  conversationId: conversationId,
  refId: refId,
);

/// Phase 1 — compose a `kv:1:taunt` (personality) as a self-send comm. The text
/// is the frame's own content; empty text is refused in `core::frames`.
Future<SignableSummaryDto> transportPrepareTaunt({
  required String conversationId,
  required String text,
}) => RustLib.instance.api.crateApiTransportTransportPrepareTaunt(
  conversationId: conversationId,
  text: text,
);

/// Phase 2: sign + broadcast the stashed transport plan identified by `nonce`.
/// Same stale-nonce refusal, partial-honesty (B6) and change-cursor discipline
/// as the payment path — one shared implementation. On a CLEAN broadcast the
/// stashed intent folds into the transport store (conversation + sent row).
Future<SendOutcomeDto> transportCommit({required BigInt nonce}) =>
    RustLib.instance.api.crateApiTransportTransportCommit(nonce: nonce);

/// Drop any stashed transport send (confirm dismissed / back). Idempotent.
Future<void> transportAbandon() =>
    RustLib.instance.api.crateApiTransportTransportAbandon();

/// All conversations, most recently active first.
Future<List<ConversationDto>> transportConversations() =>
    RustLib.instance.api.crateApiTransportTransportConversations();

/// Hide a conversation — forget its CONTENT, keep its IDENTITY.
///
/// This used to hard-delete the conversation row, and that was the defect
/// behind the worst interop failure this project has had. The row is the only
/// place the counterparty's alias lives, and their alias is the only thing
/// that routes their messages to us. Deleting it did not stop them writing —
/// it made every message they sent afterwards undeliverable, permanently,
/// because a client that already knows us never re-announces itself.
///
/// So: the messages are still purged — hide must forget what was said, and
/// the sheet copy promises exactly that — but the conversation row is
/// tombstoned rather than removed. It stops appearing in the list and stops
/// being swept for history, while remaining matchable by alias and by address
/// so an acceptance or a later message can still find its home.
///
/// Idempotent: hiding an unknown id is a no-op success.
Future<void> transportHideConversation({required String conversationId}) =>
    RustLib.instance.api.crateApiTransportTransportHideConversation(
      conversationId: conversationId,
    );

/// A conversation's thread, oldest first — DECRYPT-ON-VIEW (§0.4): sealed
/// rows open here, per call, while the vault is unlocked; the plaintext
/// crosses once as the display DTO and Dart drops it with the widget. Vault
/// locked ⇒ this errs and the thread is unreadable (the P2.3 acceptance
/// observation). Handshake rows are system rows — no body crosses.
Future<List<ThreadMessageDto>> transportThread({
  required String conversationId,
}) => RustLib.instance.api.crateApiTransportTransportThread(
  conversationId: conversationId,
);

/// Incremental thread pull (V2): decrypt ONLY the rows strictly after
/// `after_txid` in the store's `(unix_ms, txid)` order, and return the
/// current status of EVERY row so status transitions of already-rendered
/// rows (tombstone flips, acceptance progress) land without re-decrypting
/// the conversation. Cursor semantics:
///
/// - rows are write-once (`unix_ms`/`txid` never change after recording), so
///   a cursor's sort position is stable;
/// - an absent or UNKNOWN cursor (e.g. the anchor row was removed) degrades
///   to the full thread — the caller keys rows by txid, so the merge is
///   idempotent, never duplicating;
/// - a new row CAN sort behind a live cursor (inbound handshake rows carry
///   the sender-claimed `payload.timestamp`; same-ms txid tie-breaks) and
///   would then be absent from `messages` — but never from `statuses`,
///   which covers every row. THE CALLER CONTRACT: a statuses txid you have
///   never rendered means a stranded row — do one full re-pull (cursor
///   `None`), whose statuses ⊇ all rows, so it converges in one step
///   (consensus-audit V2 finding 1; the thread screen implements this).
///
/// §0.4 unchanged: decrypt-on-view, per call, vault-locked errors, plaintext
/// crosses once and dies with the widget. The tracker is a soft dependency
/// (V1 law): unavailable ⇒ `acceptance: None`, store truth stands alone.
Future<ThreadDeltaDto> transportThreadSince({
  required String conversationId,
  String? afterTxid,
}) => RustLib.instance.api.crateApiTransportTransportThreadSince(
  conversationId: conversationId,
  afterTxid: afterTxid,
);

/// The tracker's live answer for one txid (V2 sitting request: the chip
/// streams "N confirmations"). Depth is computed AT READ from the live sink
/// blue score (node-read, INV-9 — `AcceptanceTracker::status`), so a 1 Hz
/// poll of this fn yields a climbing counter. `None` = unwatched / pruned /
/// tracker unavailable — the caller's chip simply doesn't count.
Future<TxStatusDto?> txAcceptanceStatus({required String txid}) =>
    RustLib.instance.api.crateApiTransportTxAcceptanceStatus(txid: txid);

/// Sparse, content-free conversation-change pings (a conversation id) —
/// Dart re-pulls [`transport_conversations`] / [`transport_thread`] on each.
/// Nothing decrypted ever streams (§0.4: no Dart state manager holds content).
Stream<String> subscribeThreadPings() =>
    RustLib.instance.api.crateApiTransportSubscribeThreadPings();

/// Subscribe to live `ciph_msg:` matches from the BlockAdded scan. Discrete
/// deliveries, not snapshots: there is deliberately no cached-latest replay
/// (unlike `subscribe_dag_updates`) — history is the P2.3 message store's job;
/// this stream is the live wire. Foreground-only by construction: the scan
/// rides the shared socket's `dag_pause()`/`dag_resume()` posture (D-053).
Stream<TransportEventDto> subscribeTransportEvents() =>
    RustLib.instance.api.crateApiTransportSubscribeTransportEvents();

/// A conversation row for the contacts surface. Every field is public-wire-
/// class data (addresses/txids on-chain, aliases on-wire, local ids/status).
class ConversationDto {
  final String conversationId;

  /// Counterparty address — empty on an inbound-pending row until the
  /// accept flow resolves the sender via the node.
  final String contactAddress;
  final String myAlias;
  final String? theirAlias;

  /// `pending_out` / `pending_in` / `active`.
  final String status;
  final bool initiatedByMe;
  final BigInt createdUnixMs;
  final BigInt lastActivityUnixMs;

  /// A `pending_in` invitation whose bond tx is past the node's pruning
  /// horizon (V5, finding 15): the accept can NEVER resolve — the bond
  /// UTXO is spent/pruned and the return-address RPC is gone with it. The
  /// card renders the honest terminal copy + a Dismiss exit instead of the
  /// transient promise. Computed in Rust from the pin-read horizon
  /// (INV-9); only this bool crosses the FFI. Always `false` for other
  /// statuses.
  final bool inviteExpired;

  const ConversationDto({
    required this.conversationId,
    required this.contactAddress,
    required this.myAlias,
    this.theirAlias,
    required this.status,
    required this.initiatedByMe,
    required this.createdUnixMs,
    required this.lastActivityUnixMs,
    required this.inviteExpired,
  });

  @override
  int get hashCode =>
      conversationId.hashCode ^
      contactAddress.hashCode ^
      myAlias.hashCode ^
      theirAlias.hashCode ^
      status.hashCode ^
      initiatedByMe.hashCode ^
      createdUnixMs.hashCode ^
      lastActivityUnixMs.hashCode ^
      inviteExpired.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationDto &&
          runtimeType == other.runtimeType &&
          conversationId == other.conversationId &&
          contactAddress == other.contactAddress &&
          myAlias == other.myAlias &&
          theirAlias == other.theirAlias &&
          status == other.status &&
          initiatedByMe == other.initiatedByMe &&
          createdUnixMs == other.createdUnixMs &&
          lastActivityUnixMs == other.lastActivityUnixMs &&
          inviteExpired == other.inviteExpired;
}

/// The user's fill posture, for the settings surface. `default_endpoint`
/// rides along so the UI can offer "reset to default" without hardcoding it.
class FillConfigDto {
  /// Defaults OFF — the §0 lock (founder-ruled 2026-07-10): node-only out
  /// of the box; enabling is an explicit opt-in beside the disclosure.
  final bool enabled;
  final String endpoint;
  final String defaultEndpoint;

  const FillConfigDto({
    required this.enabled,
    required this.endpoint,
    required this.defaultEndpoint,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^ endpoint.hashCode ^ defaultEndpoint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FillConfigDto &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          endpoint == other.endpoint &&
          defaultEndpoint == other.defaultEndpoint;
}

/// One fill run's outcome — row counts and shape only, never content. The
/// honest-notice logic reads this: `!ran || !complete` keeps the "history
/// before X may be incomplete" notice up (never silence — D-074).
class FillReportDto {
  /// False when the fill is disabled or another run was already in flight.
  final bool ran;

  /// Every walk drained within budget and without a network error.
  final bool complete;
  final int pages;

  /// New rows folded into the store (post verify-by-decrypt + txid dedup).
  final int newRows;

  /// First network/HTTP error text, when any walk failed.
  final String? error;
  final BigInt atUnixMs;

  const FillReportDto({
    required this.ran,
    required this.complete,
    required this.pages,
    required this.newRows,
    this.error,
    required this.atUnixMs,
  });

  @override
  int get hashCode =>
      ran.hashCode ^
      complete.hashCode ^
      pages.hashCode ^
      newRows.hashCode ^
      error.hashCode ^
      atUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FillReportDto &&
          runtimeType == other.runtimeType &&
          ran == other.ran &&
          complete == other.complete &&
          pages == other.pages &&
          newRows == other.newRows &&
          error == other.error &&
          atUnixMs == other.atUnixMs;
}

/// A parsed `kv:1:` game frame (P2.4 §0.5). Fields come from the frame JSON, so
/// a tampered readable line can't misstate the card. Nothing here binds value —
/// the `stake` is a DISPLAY number; the real wager binds at the P3 covenant.
class FrameDto {
  /// `challenge` | `accept` | `result` | `taunt`.
  final String kind;

  /// `challenge`: the game slug (P2.4: `attack_defend`); empty otherwise.
  final String game;

  /// `challenge`: the DISPLAY stake in KAS; empty ⇒ a friendly, no-stake duel.
  final String stake;

  /// The challenge id this frame concerns (a `challenge`'s own id, or the id
  /// an `accept`/`result` references) — enables card pairing; empty otherwise.
  final String id;

  /// `result`: the reported outcome (a claim). `taunt`: the text. Else empty.
  final String detail;

  const FrameDto({
    required this.kind,
    required this.game,
    required this.stake,
    required this.id,
    required this.detail,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      game.hashCode ^
      stake.hashCode ^
      id.hashCode ^
      detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrameDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          game == other.game &&
          stake == other.stake &&
          id == other.id &&
          detail == other.detail;
}

/// "How much history did this open skip?" — the honest number behind V2b's
/// gap notice. All node-read data (INV-9): cursor block timestamp vs now.
class GapAgeDto {
  /// Minutes between the last-scanned block and now, when knowable.
  final BigInt? gapMinutes;

  /// True when the node no longer knows the cursor block: the gap is at
  /// least the pruning horizon (read from the pinned params — see
  /// `kaspaverse_chain::pruning_horizon_ms`), and history before it is
  /// unrecoverable from any normal node.
  final bool beyondHorizon;

  const GapAgeDto({this.gapMinutes, required this.beyondHorizon});

  static Future<GapAgeDto> default_() =>
      RustLib.instance.api.crateApiTransportGapAgeDtoDefault();

  @override
  int get hashCode => gapMinutes.hashCode ^ beyondHorizon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GapAgeDto &&
          runtimeType == other.runtimeType &&
          gapMinutes == other.gapMinutes &&
          beyondHorizon == other.beyondHorizon;
}

/// Per-txid display status for EVERY message in a conversation — the cheap
/// (no-decrypt) half of [`transport_thread_since`]. Rows already on the glass
/// apply these in place: a tombstone flip or an acceptance transition of a row
/// BEHIND the cursor would otherwise be invisible to an incremental pull (the
/// V2-design resolution of the cursor edge-case research hook).
class MessageStatusDto {
  final String txid;

  /// V1 reorg honesty (reversible ghost flag).
  final bool tombstoned;

  /// `None` = unwatched or horizon-pruned — store/wallet truth stands alone.
  final TxStatusDto? acceptance;

  const MessageStatusDto({
    required this.txid,
    required this.tombstoned,
    this.acceptance,
  });

  @override
  int get hashCode => txid.hashCode ^ tombstoned.hashCode ^ acceptance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageStatusDto &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          tombstoned == other.tombstoned &&
          acceptance == other.acceptance;
}

/// One incremental thread pull: the decrypted NEW tail plus the status of
/// every row in the conversation.
class ThreadDeltaDto {
  /// Rows strictly after the cursor in the store's `(unix_ms, txid)` order,
  /// decrypted on view (§0.4). The FULL thread when the cursor is absent or
  /// unknown — the caller keys rows by txid, so a full merge is idempotent.
  final List<ThreadMessageDto> messages;

  /// Status for every message txid in the conversation, cursor-independent.
  final List<MessageStatusDto> statuses;

  const ThreadDeltaDto({required this.messages, required this.statuses});

  @override
  int get hashCode => messages.hashCode ^ statuses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadDeltaDto &&
          runtimeType == other.runtimeType &&
          messages == other.messages &&
          statuses == other.statuses;
}

/// One thread row — [`text`](Self::text) is THE first decrypted content to
/// cross this bridge (user content post-decrypt, D-056; ffi-leak pre-cleared
/// shape). Produced only by [`transport_thread`] (decrypt-on-view, §0.4):
/// Dart renders and drops it; nothing here is cached, logged, or persisted.
class ThreadMessageDto {
  final String txid;

  /// `handshake` (a system row — no body) or `comm`.
  final String kind;
  final bool outbound;
  final BigInt unixMs;

  /// Decrypted message text for readable `comm` rows; empty otherwise. When
  /// [`frame`](Self::frame) is set this is the frame's readable line (what a
  /// Kasia user sees; the KaspaVerse card fallback), not the machine tail.
  final String text;

  /// False when no watched key opens the envelope (kept honest, not hidden).
  final bool readable;

  /// Set when the decrypted body carried a RECOGNIZED `kv:1:` game frame —
  /// the tappable arcade half. `None` for a plain message OR an unknown /
  /// forward-version tail (which render as an ordinary bubble from `text`,
  /// P5). Display-only: a frame binds no value (§0.3).
  final FrameDto? frame;

  /// V1 reorg honesty: true when this message's accepting block was
  /// displaced and not re-accepted within the observed window — the row is
  /// a ghost (styled affordance lands in V2; the flag is the truth surface).
  final bool tombstoned;

  /// Where this row came from: `node` (our node's own scan — chain truth),
  /// `archive` (a history-fill row from an indexer, D-074 — an unverifiable
  /// txid and timestamp), `own` (self-authored at commit), `unknown`
  /// (written before V5 recorded provenance).
  ///
  /// The store has recorded this since V5; it did not cross the bridge, so an
  /// archive-supplied row rendered byte-identically to node truth and the
  /// fill's disclosure promised a guarantee the wire cannot make
  /// (product-audit run 1, F3). A `String` rather than the chain crate's
  /// `RowSource`, matching [`kind`](Self::kind): the enum is a store-layer
  /// type with Borsh positional law on it, and widening its blast radius to
  /// the FFI buys nothing the label does not.
  final String provenance;

  const ThreadMessageDto({
    required this.txid,
    required this.kind,
    required this.outbound,
    required this.unixMs,
    required this.text,
    required this.readable,
    this.frame,
    required this.tombstoned,
    required this.provenance,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      kind.hashCode ^
      outbound.hashCode ^
      unixMs.hashCode ^
      text.hashCode ^
      readable.hashCode ^
      frame.hashCode ^
      tombstoned.hashCode ^
      provenance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadMessageDto &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          kind == other.kind &&
          outbound == other.outbound &&
          unixMs == other.unixMs &&
          text == other.text &&
          readable == other.readable &&
          frame == other.frame &&
          tombstoned == other.tombstoned &&
          provenance == other.provenance;
}

/// One `ciph_msg:` match from the live BlockAdded scan (P2.1 raw receive).
/// Raw by design: kind is the verbatim wire token, `body` the raw bytes after
/// it — semantics (decryption, conversations) arrive in P2.2/P2.3.
class TransportEventDto {
  /// Transaction id (hex), when resolvable — never fabricated.
  final String? txid;

  /// Wire kind: `bcast` / `handshake` / `comm` / … / `legacy` / `unknown`.
  final String kind;

  /// Raw body bytes (ciphertext or plaintext; on-chain public data).
  final Uint8List body;

  /// Output addresses of the carrying tx (recipients incl. change).
  final List<String> addresses;

  const TransportEventDto({
    this.txid,
    required this.kind,
    required this.body,
    required this.addresses,
  });

  @override
  int get hashCode =>
      txid.hashCode ^ kind.hashCode ^ body.hashCode ^ addresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportEventDto &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          kind == other.kind &&
          body == other.body &&
          addresses == other.addresses;
}

/// The acceptance tracker's answer for one txid, mirrored for display (V2
/// status chips). A RENDERING of the chain crate's `TxStatus` — depth is
/// node-read there (INV-9); nothing is recomputed here.
class TxStatusDto {
  final TxStatusKind kind;

  /// Node-read blue depth for `Accepted`/`Confirmed` (the V6
  /// observe-before-tuning surface); `None` otherwise.
  final BigInt? blueDepth;

  /// How long a `Stalled` submit has waited; `None` otherwise.
  final BigInt? waitedMs;

  const TxStatusDto({required this.kind, this.blueDepth, this.waitedMs});

  @override
  int get hashCode => kind.hashCode ^ blueDepth.hashCode ^ waitedMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxStatusDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          blueDepth == other.blueDepth &&
          waitedMs == other.waitedMs;
}

/// The five acceptance states a chip can wear (V2). Field-less — FRB 2.12
/// maps an enum-with-fields to a freezed class (the dag.rs DTO note); the
/// per-state numbers ride [`TxStatusDto`]'s optional fields instead.
enum TxStatusKind { submitted, accepted, confirmed, displaced, stalled }
