// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'send.dart';

// These functions are ignored because they are not marked as `pub`: `to_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Phase 1 (dev/broadcast lane): compose `ciph_msg:1:bcast:<channel>:<text>`,
/// build the tx chain over the live UTXO context with the payload on the final
/// tx, and stash it unsigned. Returns the Rust-decoded summary (incl. the
/// payload the BUILT tx carries) for the confirm step.
Future<TransportSendSummaryDto> transportPrepareBcast({
  required String destination,
  required BigInt amountSompi,
  required String channel,
  required String message,
}) => RustLib.instance.api.crateApiTransportTransportPrepareBcast(
  destination: destination,
  amountSompi: amountSompi,
  channel: channel,
  message: message,
);

/// Phase 2: sign + broadcast the stashed transport plan identified by `nonce`.
/// Same stale-nonce refusal, partial-honesty (B6) and change-cursor discipline
/// as the payment path — one shared implementation.
Future<SendOutcomeDto> transportCommit({required BigInt nonce}) =>
    RustLib.instance.api.crateApiTransportTransportCommit(nonce: nonce);

/// Drop any stashed transport send (confirm dismissed / back). Idempotent.
Future<void> transportAbandon() =>
    RustLib.instance.api.crateApiTransportTransportAbandon();

/// Subscribe to live `ciph_msg:` matches from the BlockAdded scan. Discrete
/// deliveries, not snapshots: there is deliberately no cached-latest replay
/// (unlike `subscribe_dag_updates`) — history is the P2.3 message store's job;
/// this stream is the live wire. Foreground-only by construction: the scan
/// rides the shared socket's `dag_pause()`/`dag_resume()` posture (D-053).
Stream<TransportEventDto> subscribeTransportEvents() =>
    RustLib.instance.api.crateApiTransportSubscribeTransportEvents();

/// One `ciph_msg:` match from the live BlockAdded scan (P2.1 raw receive).
/// Raw by design: kind is the verbatim wire token, `body` the raw bytes after
/// it — semantics (decryption, conversations) arrive in P2.2/P2.3.
class TransportEventDto {
  /// Transaction id (hex), when resolvable — never fabricated.
  final String? txid;

  /// Wire kind: `bcast` / `handshake` / `comm` / … / `legacy` / `unknown`.
  final String kind;

  /// Raw body bytes (ciphertext or plaintext; on-chain public data).
  final Uint8List body;

  /// Output addresses of the carrying tx (recipients incl. change).
  final List<String> addresses;

  const TransportEventDto({
    this.txid,
    required this.kind,
    required this.body,
    required this.addresses,
  });

  @override
  int get hashCode =>
      txid.hashCode ^ kind.hashCode ^ body.hashCode ^ addresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportEventDto &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          kind == other.kind &&
          body == other.body &&
          addresses == other.addresses;
}

/// The Rust-decoded summary the transport confirm renders (B7 — never the form
/// echo). Superset of the payment summary: `payload_len`/`payload_kind` are
/// decoded FROM THE BUILT final transaction, so the user confirms what will
/// actually be signed, payload included (anti-blind-signing parity with P1.6).
class TransportSendSummaryDto {
  /// Opaque token tying this summary to its stashed transactions.
  final BigInt nonce;

  /// The mainnet address Rust validated and built into the payment output.
  final String destination;
  final BigInt amountSompi;

  /// The Generator's exact aggregate fee — payload mass is priced in here
  /// (KIP-9; the P2.1 fee-delta proof reads this field).
  final BigInt feeSompi;

  /// `amount + fee` (what leaves the wallet, excluding returned change).
  final BigInt totalSompi;
  final BigInt mass;
  final int txCount;
  final int utxoCount;

  /// Payload bytes on the built final tx (read back, not echoed).
  final int payloadLen;

  /// Wire kind decoded from the built payload (`bcast` here) — same parser
  /// the receive scan uses.
  final String payloadKind;

  const TransportSendSummaryDto({
    required this.nonce,
    required this.destination,
    required this.amountSompi,
    required this.feeSompi,
    required this.totalSompi,
    required this.mass,
    required this.txCount,
    required this.utxoCount,
    required this.payloadLen,
    required this.payloadKind,
  });

  @override
  int get hashCode =>
      nonce.hashCode ^
      destination.hashCode ^
      amountSompi.hashCode ^
      feeSompi.hashCode ^
      totalSompi.hashCode ^
      mass.hashCode ^
      txCount.hashCode ^
      utxoCount.hashCode ^
      payloadLen.hashCode ^
      payloadKind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportSendSummaryDto &&
          runtimeType == other.runtimeType &&
          nonce == other.nonce &&
          destination == other.destination &&
          amountSompi == other.amountSompi &&
          feeSompi == other.feeSompi &&
          totalSompi == other.totalSompi &&
          mass == other.mass &&
          txCount == other.txCount &&
          utxoCount == other.utxoCount &&
          payloadLen == other.payloadLen &&
          payloadKind == other.payloadKind;
}
