// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `active_until`, `atomic_write`, `blob_path`, `broadcast_status`, `current_status`, `export_seed_for_keystore`, `from_bytes`, `is_unlocked`, `load_vault_from_seed_bytes`, `lockout_delay_secs`, `lockout_path`, `now_unix`, `read_blob`, `read_lockout`, `set_vault`, `status_tx`, `to_bytes`, `vault_dir`, `write_lockout`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Lockout`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `from`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// Hand the bridge the platform's app-private directory (INV-3). Idempotent
/// for the same path (hot restart re-calls it); a later call with a DIFFERENT
/// path is refused — silently re-homing the vault would strand the blob and
/// the lockout state where no caller looks (custody, not configuration).
Future<void> initVault({required String appPrivateDir}) =>
    RustLib.instance.api.crateApiVaultInitVault(appPrivateDir: appPrivateDir);

/// Subscribe to vault status. Paints the current state immediately, then on
/// every change. One stream per process; survives Dart hot restart (re-attach).
Stream<VaultStatus> vaultStatusStream() =>
    RustLib.instance.api.crateApiVaultVaultStatusStream();

/// Whether a sealed blob exists at rest.
Future<bool> vaultExists() => RustLib.instance.api.crateApiVaultVaultExists();

/// Enroll mechanism (P1 §0.4, Path B). Generates a fresh 12-word seed, seals it
/// under `passphrase`, writes the blob atomically, leaves the vault unlocked.
///
/// **The word-reveal + verification ceremony is P1.4** — this mechanism stands
/// up a recoverable vault so the unlock/lock loop is testable; it deliberately
/// never surfaces the phrase (INV-1: words never cross FRB). Path-A biometric is
/// layered on afterwards by the Kotlin Keystore path via the JNI enroll export.
Future<void> createVault({
  required List<int> passphrase,
  required VaultKdfParams params,
}) => RustLib.instance.api.crateApiVaultCreateVault(
  passphrase: passphrase,
  params: params,
);

/// Unlock via passphrase (Path B). Rate-limit is checked BEFORE the KDF runs
/// (wallet-security 11), so a locked-out attempt costs nothing. On failure the
/// attempt counter advances and persists; on success it resets.
Future<void> unlockWithPassphrase({required List<int> passphrase}) => RustLib
    .instance
    .api
    .crateApiVaultUnlockWithPassphrase(passphrase: passphrase);

/// Lock the vault. **Contract (D-031.4): "no new operation can start", not
/// "instant erasure".** A sign already in flight holds an upgraded strong ref
/// (from the core Arc/Weak design) and completes; the seed zeroizes when that
/// last ref drops. This fn intentionally exposes no "erased" flag — `VaultStatus`
/// reports `unlocked=false` only — so the bridge can never assert erasure while
/// a sign is concurrently finishing. Also the Flutter lifecycle hook: Dart calls
/// this on background/detach.
Future<void> lockVault() => RustLib.instance.api.crateApiVaultLockVault();

/// Argon2id cost parameters chosen by on-device tuning (P1.2 §0.3). Mapped onto
/// the core `SealParams`, which bounds-checks them (8 MiB..=256 MiB, D-031.2).
class VaultKdfParams {
  final int mCostKib;
  final int tCost;
  final int pCost;

  const VaultKdfParams({
    required this.mCostKib,
    required this.tCost,
    required this.pCost,
  });

  /// The v1 starting grid (P1 §0.3): m = 64 MiB, t = 3, p = 1. P1.2 device
  /// tuning replaces this with a measured point recorded in
  /// PERFORMANCE_BUDGET.md.
  static Future<VaultKdfParams> startingGrid() =>
      RustLib.instance.api.crateApiVaultVaultKdfParamsStartingGrid();

  @override
  int get hashCode => mCostKib.hashCode ^ tCost.hashCode ^ pCost.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultKdfParams &&
          runtimeType == other.runtimeType &&
          mCostKib == other.mCostKib &&
          tCost == other.tCost &&
          pCost == other.pCost;
}

/// What Dart may observe about the vault — bools and non-secret counters only.
class VaultStatus {
  /// A sealed blob exists at rest (a wallet has been created).
  final bool exists;

  /// The vault is currently unlocked in memory.
  final bool unlocked;

  /// If rate-limited, the unix time (s) until which unlock is refused.
  final BigInt? lockedOutUntilUnix;

  /// Consecutive failed unlock attempts (resets to 0 on any success).
  final int failedAttempts;

  const VaultStatus({
    required this.exists,
    required this.unlocked,
    this.lockedOutUntilUnix,
    required this.failedAttempts,
  });

  static Future<VaultStatus> default_() =>
      RustLib.instance.api.crateApiVaultVaultStatusDefault();

  @override
  int get hashCode =>
      exists.hashCode ^
      unlocked.hashCode ^
      lockedOutUntilUnix.hashCode ^
      failedAttempts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultStatus &&
          runtimeType == other.runtimeType &&
          exists == other.exists &&
          unlocked == other.unlocked &&
          lockedOutUntilUnix == other.lockedOutUntilUnix &&
          failedAttempts == other.failedAttempts;
}
