// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `active_until`, `atomic_write`, `blob_path`, `broadcast_status`, `build_wallet_signer`, `chain_store_dir`, `change_address_at`, `change_cursor_path`, `change_cursor`, `current_status`, `derive_wallet_addresses`, `endpoint_cache_path`, `export_seed_for_keystore`, `from_bytes`, `is_unlocked`, `load_vault_from_seed_bytes`, `lockout_delay_secs`, `lockout_path`, `now_unix`, `read_blob`, `read_lockout`, `reveal_ceremony_words`, `scan_high_water`, `scan_window_path`, `set_change_cursor`, `set_scan_high_water`, `set_vault`, `status_tx`, `to_bytes`, `transport_decryptor`, `transport_store_dir`, `vault_dir`, `wallet_address_at`, `wallet_store_path`, `write_lockout`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Lockout`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `from`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// The wallet's primary receive address (receive index 0), for the Receive
/// sheet. An address is PUBLIC (derived from the account xpub) — INV-1 governs
/// secrets, not addresses — so it may cross the FFI. Errors if the vault is
/// locked. (Next-unused-address rotation is deferred; P1.5 shows index 0.)
Future<String> vaultReceiveAddress() =>
    RustLib.instance.api.crateApiVaultVaultReceiveAddress();

/// Hand the bridge the platform's app-private directory (INV-3). Idempotent
/// for the same path (hot restart re-calls it); a later call with a DIFFERENT
/// path is refused — silently re-homing the vault would strand the blob and
/// the lockout state where no caller looks (custody, not configuration).
Future<void> initVault({required String appPrivateDir}) =>
    RustLib.instance.api.crateApiVaultInitVault(appPrivateDir: appPrivateDir);

/// Subscribe to vault status. Paints the current state immediately, then on
/// every change. One stream per process; survives Dart hot restart (re-attach).
Stream<VaultStatus> vaultStatusStream() =>
    RustLib.instance.api.crateApiVaultVaultStatusStream();

/// Whether a sealed blob exists at rest.
Future<bool> vaultExists() => RustLib.instance.api.crateApiVaultVaultExists();

/// Begin a create ceremony: generate a fresh 12-word mnemonic and hold it for
/// the native reveal/verify surface. Refuses if a vault already exists (one
/// wallet per install) or a ceremony is already in progress (seal or abandon the
/// prior one first). The phrase never crosses FRB.
Future<void> beginCreate() => RustLib.instance.api.crateApiVaultBeginCreate();

/// Abandon an in-progress create ceremony (back-gesture / cancel): drops the
/// held mnemonic, zeroizing the phrase. Idempotent (a no-op if none is held).
Future<void> abandonCreate() =>
    RustLib.instance.api.crateApiVaultAbandonCreate();

/// Complete a create ceremony: seal the held mnemonic's seed under `passphrase`,
/// persist the blob atomically, and leave the vault unlocked. The optional
/// `extra_word` (13th word / BIP39 passphrase) is restricted to **ASCII** on the
/// create path (D-031.5; `mnemonic.rs::into_seed`): the pinned `to_seed` does no
/// NFKD, so a non-ASCII extra word would silently derive a different wallet on a
/// normalizing implementation — refused here so a NEW backup stays portable. The
/// cheap checks (ASCII, vault-absent, ceremony-present) run BEFORE the ceremony
/// is consumed, so a rejected attempt leaves it held for a retry.
Future<void> sealAndPersist({
  required List<int> passphrase,
  required List<int> extraWord,
  required VaultKdfParams params,
}) => RustLib.instance.api.crateApiVaultSealAndPersist(
  passphrase: passphrase,
  extraWord: extraWord,
  params: params,
);

/// Restore preview (deliverable 2 — the decoy/typo trap): derive the FIRST
/// receive address from a candidate phrase WITHOUT persisting or unlocking. A
/// single wrong word opens a visibly DIFFERENT wallet, so surfacing the derived
/// address lets the user catch a typo before committing instead of landing in a
/// silent empty wallet. The address is public (INV-2 permits it to cross);
/// `phrase`/`extra_word` are the user's `Uint8List`, wiped Dart-side after the
/// call (INV-1 sentence two). Restore accepts any UTF-8 extra word (max
/// compatibility — unlike the ASCII-only create path).
Future<String> restorePreview({
  required List<int> phrase,
  required List<int> extraWord,
}) => RustLib.instance.api.crateApiVaultRestorePreview(
  phrase: phrase,
  extraWord: extraWord,
);

/// Restore-commit (deliverable 2): restore from `phrase` (+ optional
/// `extra_word`), seal the derived seed under `passphrase`, persist, unlock.
/// Refuses if a vault already exists. Any-UTF-8 extra word (restore is the
/// compatibility path; the ASCII restriction is create-only).
Future<void> restoreAndPersist({
  required List<int> phrase,
  required List<int> extraWord,
  required List<int> passphrase,
  required VaultKdfParams params,
}) => RustLib.instance.api.crateApiVaultRestoreAndPersist(
  phrase: phrase,
  extraWord: extraWord,
  passphrase: passphrase,
  params: params,
);

/// Unlock via passphrase (Path B). Rate-limit is checked BEFORE the KDF runs
/// (wallet-security 11), so a locked-out attempt costs nothing. On failure the
/// attempt counter advances and persists; on success it resets. Attempts are
/// serialized by [`UNLOCK_GATE`] so every failure is counted.
Future<void> unlockWithPassphrase({required List<int> passphrase}) => RustLib
    .instance
    .api
    .crateApiVaultUnlockWithPassphrase(passphrase: passphrase);

/// Lock the vault. **Contract (D-031.4): "no new operation can start", not
/// "instant erasure".** A sign already in flight holds an upgraded strong ref
/// (from the core Arc/Weak design) and completes; the seed zeroizes when that
/// last ref drops. This fn intentionally exposes no "erased" flag — `VaultStatus`
/// reports `unlocked=false` only — so the bridge can never assert erasure while
/// a sign is concurrently finishing. Also the Flutter lifecycle hook: Dart calls
/// this on background/detach.
Future<void> lockVault() => RustLib.instance.api.crateApiVaultLockVault();

/// Time one Argon2id run at `params` on THIS device (P1.2 §0.3 tuning):
/// seals a throwaway seed under a dummy passphrase and returns elapsed
/// milliseconds. No secrets involved; bounds-checked by the core
/// (8 MiB..=256 MiB, D-031.2). Runs on FRB's worker pool like the real KDF.
Future<BigInt> kdfBenchMs({required VaultKdfParams params}) =>
    RustLib.instance.api.crateApiVaultKdfBenchMs(params: params);

/// Argon2id cost parameters chosen by on-device tuning (P1.2 §0.3). Mapped onto
/// the core `SealParams`, which bounds-checks them (8 MiB..=256 MiB, D-031.2).
class VaultKdfParams {
  final int mCostKib;
  final int tCost;
  final int pCost;

  const VaultKdfParams({
    required this.mCostKib,
    required this.tCost,
    required this.pCost,
  });

  /// The v1 starting grid (P1 §0.3): m = 64 MiB, t = 3, p = 1. Kept for
  /// reference/benching; new vaults use [`VaultKdfParams::tuned`].
  static Future<VaultKdfParams> startingGrid() =>
      RustLib.instance.api.crateApiVaultVaultKdfParamsStartingGrid();

  /// The P1.2 on-device tuned point (LG V60, release build, 2026-06-13):
  /// m = 192 MiB → 679 ms measured, ~32% headroom under the ≤1.0 s unlock
  /// budget — 256 MiB measured 910 ms, too close to the edge for field
  /// thermal/load variance (D-026: a budget miss is a finding). Full grid
  /// in PERFORMANCE_BUDGET.md. Default for new vaults; the blob header
  /// carries whatever a vault was actually sealed with.
  static Future<VaultKdfParams> tuned() =>
      RustLib.instance.api.crateApiVaultVaultKdfParamsTuned();

  @override
  int get hashCode => mCostKib.hashCode ^ tCost.hashCode ^ pCost.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultKdfParams &&
          runtimeType == other.runtimeType &&
          mCostKib == other.mCostKib &&
          tCost == other.tCost &&
          pCost == other.pCost;
}

/// What Dart may observe about the vault — bools and non-secret counters only.
class VaultStatus {
  /// A sealed blob exists at rest (a wallet has been created).
  final bool exists;

  /// The vault is currently unlocked in memory.
  final bool unlocked;

  /// If rate-limited, the unix time (s) until which unlock is refused.
  final BigInt? lockedOutUntilUnix;

  /// Consecutive failed unlock attempts (resets to 0 on any success).
  final int failedAttempts;

  const VaultStatus({
    required this.exists,
    required this.unlocked,
    this.lockedOutUntilUnix,
    required this.failedAttempts,
  });

  static Future<VaultStatus> default_() =>
      RustLib.instance.api.crateApiVaultVaultStatusDefault();

  @override
  int get hashCode =>
      exists.hashCode ^
      unlocked.hashCode ^
      lockedOutUntilUnix.hashCode ^
      failedAttempts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultStatus &&
          runtimeType == other.runtimeType &&
          exists == other.exists &&
          unlocked == other.unlocked &&
          lockedOutUntilUnix == other.lockedOutUntilUnix &&
          failedAttempts == other.failedAttempts;
}
