// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fold`, `map_activity`, `snapshots`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Subscribe to live wallet snapshots (balance + activity) for the unlocked
/// vault's addresses. The first call starts the sync engine; later calls share
/// it. Errors if the vault is locked (the Dart side retries after unlock).
Stream<WalletSnapshot> subscribeWalletUpdates() =>
    RustLib.instance.api.crateApiWalletSubscribeWalletUpdates();

/// Direction of an activity row (mapped from the wallet framework's typed
/// transaction data). Receive-only at P1.5; outgoing/change rows arrive with
/// send (P1.6).
enum ActivityDirection { incoming, outgoing, change }

/// One activity row crossing the FFI. `*_sompi` / DAA stay `u64` (Dart `BigInt`,
/// L3); public chain data only.
class ActivityRecord {
  final String txid;
  final BigInt valueSompi;
  final BigInt? unixtimeMsec;
  final BigInt blockDaaScore;
  final ActivityDirection direction;
  final bool isCoinbase;
  final MaturityState maturity;

  const ActivityRecord({
    required this.txid,
    required this.valueSompi,
    this.unixtimeMsec,
    required this.blockDaaScore,
    required this.direction,
    required this.isCoinbase,
    required this.maturity,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      valueSompi.hashCode ^
      unixtimeMsec.hashCode ^
      blockDaaScore.hashCode ^
      direction.hashCode ^
      isCoinbase.hashCode ^
      maturity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActivityRecord &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          valueSompi == other.valueSompi &&
          unixtimeMsec == other.unixtimeMsec &&
          blockDaaScore == other.blockDaaScore &&
          direction == other.direction &&
          isCoinbase == other.isCoinbase &&
          maturity == other.maturity;
}

/// Maturity of an activity row (from `TransactionRecord::maturity()` at the
/// live DAA — never our own threshold; INV-9).
enum MaturityState { pending, confirmed }

/// Live wallet state, streamed on every change. Balances are `Option` so the UI
/// can tell "not synced yet" (`None` → DS-1 unknown `—`) from a real, live zero
/// (`Some(0)` → an empty wallet shows `0.00000000`, never unknown). A plain
/// struct, not an enum-with-fields (FRB DTO note, `dag.rs`).
class WalletSnapshot {
  final bool connected;

  /// Between `UtxoProcStart` and the first balance — the initial scan.
  final bool syncing;

  /// The connected node has no UTXO index (INV-8 honest degrade).
  final bool utxoIndexMissing;
  final BigInt? matureSompi;
  final BigInt? pendingSompi;
  final BigInt? outgoingSompi;

  /// Newest-first, capped by the chain layer.
  final List<ActivityRecord> activity;
  final String? error;

  const WalletSnapshot({
    required this.connected,
    required this.syncing,
    required this.utxoIndexMissing,
    this.matureSompi,
    this.pendingSompi,
    this.outgoingSompi,
    required this.activity,
    this.error,
  });

  static Future<WalletSnapshot> default_() =>
      RustLib.instance.api.crateApiWalletWalletSnapshotDefault();

  @override
  int get hashCode =>
      connected.hashCode ^
      syncing.hashCode ^
      utxoIndexMissing.hashCode ^
      matureSompi.hashCode ^
      pendingSompi.hashCode ^
      outgoingSompi.hashCode ^
      activity.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletSnapshot &&
          runtimeType == other.runtimeType &&
          connected == other.connected &&
          syncing == other.syncing &&
          utxoIndexMissing == other.utxoIndexMissing &&
          matureSompi == other.matureSompi &&
          pendingSompi == other.pendingSompi &&
          outgoingSompi == other.outgoingSompi &&
          activity == other.activity &&
          error == other.error;
}
